BEGIN TRANSACTION;
CREATE TABLE i3geoadmin_acessostema (codigo_tema TEXT, nacessos NUMERIC,dia NUMERIC, mes NUMERIC, ano NUMERIC);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',5,1,2,11);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,1,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,1,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,24,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,24,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,27,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,28,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,28,2,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,1,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,1,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,1,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,2,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,2,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,2,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,2,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,4,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,4,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,4,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,4,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testezoom',1,10,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,10,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomaerro',1,11,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,11,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,11,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,11,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,11,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,12,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomaerro',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomaerro',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomaerro',1,17,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,17,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,18,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,18,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,18,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,18,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,19,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,21,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,21,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,22,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,23,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,23,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,23,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,23,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,29,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,30,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testezoom',1,30,3,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,1,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,2,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,4,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,5,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,5,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,5,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,8,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomaerro',1,8,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,8,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,26,4,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,10,5,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,11,5,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,11,5,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,13,5,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,5,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,5,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testeutf8postgis',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testesubsstring',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testesubsstring',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testesubsstring',1,6,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,7,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,9,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,9,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,9,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,9,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('povoado',1,9,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('autolegenda_exemplo',1,18,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,18,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,18,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomaerro',1,18,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,21,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,27,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,28,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,28,6,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,1,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,4,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,5,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testeutf8postgis',1,6,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testeutf8postgis',1,6,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testeutf8postgis',1,6,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,7,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashpwms',1,8,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testeutf8postgis',1,29,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,29,7,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,10,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,17,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,30,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,30,8,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,10,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('autolegenda_exemplo',1,15,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('autolegenda_exemplo',1,15,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('autolegenda_exemplo',1,15,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('autolegenda_exemplo',1,15,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,19,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('estadosl',1,27,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,27,9,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,5,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,5,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,5,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,6,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testeutf8postgis',1,7,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,20,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,10,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,25,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('testephp',1,27,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,29,11,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,10,12,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,10,12,2011);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,5,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,13,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,17,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,18,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,18,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('geopr_sipam_arco',1,19,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,24,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,29,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,31,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,31,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,31,1,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,6,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,6,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,6,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,6,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('cbersgeo',1,7,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,8,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,10,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,13,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,13,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('atlas_ucse',1,13,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,14,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,15,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,16,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,17,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,19,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,20,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,24,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('testezoom',1,25,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('biomashp',1,27,2,2012);
INSERT INTO i3geoadmin_acessostema VALUES('locali',1,22,4,2012);
CREATE TABLE i3geoadmin_atlas (publicado_atlas TEXT, ordem_atlas NUMERIC, basemapfile_atlas TEXT, desc_atlas TEXT, h_atlas NUMERIC, icone_atlas TEXT, id_atlas INTEGER PRIMARY KEY, link_atlas TEXT, pranchadefault_atlas TEXT, template_atlas TEXT, tipoguias_atlas TEXT, titulo_atlas TEXT, w_atlas NUMERIC);
INSERT INTO i3geoadmin_atlas VALUES('',0,'','Esse é um texto mais longo com a descrição do atlas',500,'../imagens/atlas_icone2.jpg',1,'testemaisinfo.htm','','http://localhost/i3geo/atlas/geral.htm','expandida','BR-163',500);
INSERT INTO i3geoadmin_atlas VALUES('',1,'','',380,'../imagens/atlas_icone1.jpg',2,'','','../atlas/geral.htm','combo','Unidades de conservação',400);
INSERT INTO i3geoadmin_atlas VALUES(NULL,2,NULL,'Atlas para testes - sem h e w',NULL,'../imagens/atlas_icone1.jpg',3,NULL,NULL,'../atlas/geral.htm',NULL,'Teste sem w e h',NULL);
INSERT INTO i3geoadmin_atlas VALUES('',3,'','',0,'',4,'','','','','Meu novo Atlas',0);
CREATE TABLE i3geoadmin_atlasp (ordem_prancha NUMERIC, desc_prancha TEXT, h_prancha NUMERIC, icone_prancha TEXT, id_atlas NUMERIC, id_prancha INTEGER PRIMARY KEY, link_prancha TEXT, mapext_prancha TEXT, titulo_prancha TEXT, w_prancha NUMERIC);
INSERT INTO i3geoadmin_atlasp VALUES(0,'Teste da prancha 1',200,'',1,1,'','-82,-39,-23,9','Pranchax 1',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(0,'',NULL,'../imagens/minipizza.gif',2,2,'http://mapas.mma.gov.br/geodados/brasil/areasespec/atlas_ucs.html','-82,-39,-23,9','Todas',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(1,'',NULL,'../imagens/minipizza.gif',2,3,'http://mapas.mma.gov.br/geodados/brasil/areasespec/atlas_ucs.html','-82,-39,-23,9','Estaduais de proteção integral',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(2,'',NULL,'../imagens/minipizza.gif',2,4,'http://mapas.mma.gov.br/geodados/brasil/areasespec/atlas_ucs.html','-82,-39,-23,9','Federais de proteção integral',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(3,'',NULL,'../imagens/minipizza.gif',2,5,'','-82,-39,-23,9','Teste de guia 1',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(4,'',NULL,'../imagens/minipizza.gif',2,6,'','-82,-39,-23,9','Teste de guia 2',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(5,'',NULL,'../imagens/minipizza.gif',2,7,'','-82,-39,-23,9','Teste de guia 3',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(6,'',NULL,'../imagens/minipizza.gif',2,8,'','-82,-39,-23,9','Teste de guia 4',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(7,'',NULL,'../imagens/minipizza.gif',2,9,'','-82,-39,-23,9','Teste de guia 5',NULL);
INSERT INTO i3geoadmin_atlasp VALUES(1,'',0,'',3,10,'','','test',0);
INSERT INTO i3geoadmin_atlasp VALUES(2,'',0,'',3,11,'','','xxxx',0);
INSERT INTO i3geoadmin_atlasp VALUES(1,'',0,'',4,12,'','','Minha nova prancha',0);
CREATE TABLE i3geoadmin_atlast (ordem_tema NUMERIC, codigo_tema TEXT, id_prancha TEXT, id_tema INTEGER PRIMARY KEY, ligado_tema TEXT);
INSERT INTO i3geoadmin_atlast VALUES(0,'estadosl',1,1,'SIM');
INSERT INTO i3geoadmin_atlast VALUES(1,'biomashp',1,2,'SIM');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',2,3,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsef',2,4,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',3,5,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucse',3,6,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',4,7,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsf',4,8,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',5,9,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsf',5,10,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',6,11,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsf',6,12,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',7,13,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsf',7,14,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',8,15,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsf',8,16,'sim');
INSERT INTO i3geoadmin_atlast VALUES(0,'atlas_biomas',9,17,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucsf',9,18,'sim');
INSERT INTO i3geoadmin_atlast VALUES(1,'atlas_ucse',11,19,'');
INSERT INTO i3geoadmin_atlast VALUES(1,'biomashp',12,20,'SIM');
CREATE TABLE i3geoadmin_comentarios (comentario TEXT, data TEXT, openidnome TEXT, openidimagem TEXT, openidservico TEXT, openidusuario TEXT, openidurl TEXT, id_tema NUMERIC);
INSERT INTO i3geoadmin_comentarios VALUES('teste',NULL,NULL,NULL,NULL,NULL,NULL,0);
INSERT INTO i3geoadmin_comentarios VALUES('sdfasdfasdfasdfasdfasdf sdvav swdfjaoskdfn asdjfkj sdf,m ansdmfnknasd fkjnjasdfkljlkasdf lkasjdfkjskldfjklasdf kjasdfkojsadjf askdjfkojasdklfjskld sdfasdfasdfasdfasdfasdf sdvav swdfjaoskdfn asdjfkj sdf,m ansdmfnknasd fkjnjasdfkljlkasdf lkasjdfkjskldfjklasdf kjasdfkojsadjf askdjfkojasdklfjskld','29-11-2010T20:29:15Z','edmar.moretti','','google','edmar.moretti','http://www.google.com/profiles/edmar.moretti',72);
CREATE TABLE i3geoadmin_grupos (it TEXT, es TEXT, en TEXT, desc_grupo TEXT, id_grupo INTEGER PRIMARY KEY, nome_grupo TEXT);
INSERT INTO i3geoadmin_grupos VALUES('Ambiente físico e biodiversidade','Ambiente físico e biodiversidade','Ambiente físico e biodiversidade','Biomas, vegetação, áreas prioritárias para conservação, etc.',1,'Ambiente físico e biodiversidade');
INSERT INTO i3geoadmin_grupos VALUES('Edite o arquivo i3geo/menutemas/menutemas.xml!!!','Edite o arquivo i3geo/menutemas/menutemas.xml!!!','Edite o arquivo i3geo/menutemas/menutemas.xml!!!','',2,'Edite o arquivo i3geo/menutemas/menutemas.xml!!!');
INSERT INTO i3geoadmin_grupos VALUES('Agência Nacional de Energia Elétrica','Agência Nacional de Energia Elétrica','Agência Nacional de Energia Elétrica','',3,'Agência Nacional de Energia Elétrica');
INSERT INTO i3geoadmin_grupos VALUES('Instituto Nacional de Pesquisas Espaciais','Instituto Nacional de Pesquisas Espaciais','Instituto Nacional de Pesquisas Espaciais','',4,'Instituto Nacional de Pesquisas Espaciais');
INSERT INTO i3geoadmin_grupos VALUES('Sistema de Protecao da Amazonia','Sistema de Protecao da Amazonia','Sistema de Protecao da Amazonia','',5,'Sistema de Protecao da Amazonia');
INSERT INTO i3geoadmin_grupos VALUES('Agência Nacional das Águas','Agência Nacional das Águas','Agência Nacional das Águas','',6,'Agência Nacional das Águas');
INSERT INTO i3geoadmin_grupos VALUES('Agricultura, Extrativismo e Pesca','Agricultura, Extrativismo e Pesca','Agricultura, Extrativismo e Pesca','',7,'Agricultura, Extrativismo e Pesca');
INSERT INTO i3geoadmin_grupos VALUES('Ciência, Informação e Comunicação','Ciência, Informação e Comunicação','Ciência, Informação e Comunicação','',8,'Ciência, Informação e Comunicação');
INSERT INTO i3geoadmin_grupos VALUES('Comércio, Serviços e Turismo','Comércio, Serviços e Turismo','Comércio, Serviços e Turismo','',9,'Comércio, Serviços e Turismo');
INSERT INTO i3geoadmin_grupos VALUES('Cultura , Lazer e Esporte','Cultura , Lazer e Esporte','Cultura , Lazer e Esporte','',10,'Cultura , Lazer e Esporte');
INSERT INTO i3geoadmin_grupos VALUES('Defesa e Segurança','Defesa e Segurança','Defesa e Segurança','',11,'Defesa e Segurança');
INSERT INTO i3geoadmin_grupos VALUES('Economia e Finanças','Economia e Finanças','Economia e Finanças','',12,'Economia e Finanças');
INSERT INTO i3geoadmin_grupos VALUES('Educação','Educação','Educação','',13,'Educação');
INSERT INTO i3geoadmin_grupos VALUES('Governo e Política','Governo e Política','Governo e Política','',14,'Governo e Política');
INSERT INTO i3geoadmin_grupos VALUES('Habitação, Saneamento e Urbanismo','Habitação, Saneamento e Urbanismo','Habitação, Saneamento e Urbanismo','',15,'Habitação, Saneamento e Urbanismo');
INSERT INTO i3geoadmin_grupos VALUES('Indústria','Indústria','Indústria','',16,'Indústria');
INSERT INTO i3geoadmin_grupos VALUES('Justiça e Legislação','Justiça e Legislação','Justiça e Legislação','',17,'Justiça e Legislação');
INSERT INTO i3geoadmin_grupos VALUES('Meio Ambiente','Meio Ambiente','Meio Ambiente','',18,'Meio Ambiente');
INSERT INTO i3geoadmin_grupos VALUES('Pessoa, Família e Sociedade','Pessoa, Família e Sociedade','Pessoa, Família e Sociedade','',19,'Pessoa, Família e Sociedade');
INSERT INTO i3geoadmin_grupos VALUES('Relações Internacionais','Relações Internacionais','Relações Internacionais','',20,'Relações Internacionais');
INSERT INTO i3geoadmin_grupos VALUES('Saúde','Saúde','Saúde','',21,'Saúde');
INSERT INTO i3geoadmin_grupos VALUES('Trabalho','Trabalho','Trabalho','',22,'Trabalho');
INSERT INTO i3geoadmin_grupos VALUES('Transportes e trânsito','Transportes e trânsito','Transportes e trânsito','',23,'Transportes e trânsito');
INSERT INTO i3geoadmin_grupos VALUES('Grupo teste','Grupo teste','Test group english','',24,'Grupo teste');
INSERT INTO i3geoadmin_grupos VALUES('Grupo teste postgis','Grupo teste postgis','Group teste postgis','',25,'Grupo teste postgis');
INSERT INTO i3geoadmin_grupos VALUES('Testando a acentuação Ááó','Testando a acentuação Ááó','Testando a acentuação Ááó','',26,'Testando a acentuação Ááó');
INSERT INTO i3geoadmin_grupos VALUES('','','','',27,'Grupo sem subgrupo');
INSERT INTO i3geoadmin_grupos VALUES('','','','',28,'Grupo teste perfil teste');
CREATE TABLE i3geoadmin_identifica (publicado_i TEXT, abrir_i TEXT, id_i INTEGER PRIMARY KEY, nome_i TEXT, target_i TEXT);
INSERT INTO i3geoadmin_identifica VALUES('SIM','http://mapas.mma.gov.br/mapas/aplic/dadosdoc/buscamun.php',1,'Município - IBGE','self');
INSERT INTO i3geoadmin_identifica VALUES('NAO','http://mapas.mma.gov.br/mapas/aplic/dadosdoc/buscaeduca.php',2,'Escolas censo 2006','self');
INSERT INTO i3geoadmin_identifica VALUES('NAO','http://mapas.mma.gov.br/mapas/aplic/dadosdoc/buscasaude.php',3,'Saúde','self');
INSERT INTO i3geoadmin_identifica VALUES('NAO','http://mapas.mma.gov.br/mapas/aplic/sigepro2/lista_cruza_regioes.php',4,'SIGEPRO - ações do MMA','');
INSERT INTO i3geoadmin_identifica VALUES('NAO','http://mapas.mma.gov.br/mapas/aplic/dadosdoc/buscascielo.php',5,'Scielo','self');
INSERT INTO i3geoadmin_identifica VALUES('SIM','../ferramentas/googlemaps/endereco.php',6,'Endereço','self');
INSERT INTO i3geoadmin_identifica VALUES('SIM','../ferramentas/metar/metarproxima.php',7,'Estação METAR próxima','self');
INSERT INTO i3geoadmin_identifica VALUES('SIM','../ferramentas/identifica/twitter.php',8,'Twitter','self');
INSERT INTO i3geoadmin_identifica VALUES('','../ferramentas/identifica/twitterplaces.php',9,'Twitter lugares','');
INSERT INTO i3geoadmin_identifica VALUES('SIM','../ferramentas/geonames/opentouchmaps.php',10,'Abrir em um celular ou dispositivos móveis','new');
CREATE TABLE i3geoadmin_mapas (publicado_mapa TEXT, ordem_mapa NUMERIC, perfil_mapa TEXT, ligados_mapa TEXT, temas_mapa TEXT, desc_mapa TEXT, ext_mapa TEXT, id_mapa INTEGER PRIMARY KEY, imagem_mapa TEXT, linkdireto_mapa TEXT, nome_mapa TEXT, outros_mapa TEXT);
INSERT INTO i3geoadmin_mapas VALUES('','null','teste teste1','estadosl','cprmbrasilmag1 cprmbrasilgama1 cprmlito1 cprmfontes1 ucsfus ucsfi transporte hidrografia cprmrecmin1 cprmsedcor1 cprmpaleo1 cprmarcosaltos1 cprmestrut1 cprmfeicao1 cprmbat1 cprmcurvas1 cprmpisopacas1 cprmpto1 cprmkimb1 cprmoleo1 municip locali estadosl','Cartas geológicas da CPRM','',1,'http://mapas.mma.gov.br/i3geo/imagens/banner_cprm.png','','Cartas geológicas do Brasil','interface=http://mapas.mma.gov.br/mapas/aplic/cartasgeo/interface.htm');
INSERT INTO i3geoadmin_mapas VALUES('SIM','null','','biomashp estadosl','biomashp estadosl','Biodiversidade Brasileira','',2,'http://mapas.mma.gov.br/i3geo/imagens/banner_biodiversidade.png','','Biodiversidade','');
INSERT INTO i3geoadmin_mapas VALUES('',NULL,'','estados mundo municip estadosl','municip micro2001 meso2001 locali estadosl','Municípios, cidades e estados','',3,'http://mapas.mma.gov.br/i3geo/imagens/banner_limites.png','','Limites políticos','');
INSERT INTO i3geoadmin_mapas VALUES('',NULL,'','estados mundo amazlegal estadosl','amazlegal br163 zeeam_vege zeeam_bio modelo_elevacao agroecolog_embrapa bioma probio glc2000 pdigital1997 pdigital2000 pdigital2001 pdigital2002 pdigital2003 pdigital2004 ucsfus ucsfi ucsei ucseu indi hidrografia transporte aeroporto usina locali municip estadosl','Mapa da Amazônia Brasileira','-81.3665752271 -18.8315900519 -36.3219498753 5.66016252165',4,' http://mapas.mma.gov.br/i3geo/imagens/banner_amazonia.png','','Amazônia','');
INSERT INTO i3geoadmin_mapas VALUES('',NULL,'','','','Áreas prioritárias para conservação - 2004 - depreciado
','',5,'http://mapas.mma.gov.br/i3geo/imagens/banner_probio.png','http://mapas.mma.gov.br/mapas/aplic/probio/index.htm','Áreas prioritárias para conservação - 2004','');
CREATE TABLE i3geoadmin_menus (it TEXT, es TEXT, en TEXT, publicado_menu TEXT, perfil_menu TEXT, aberto TEXT, desc_menu TEXT, id_menu INTEGER PRIMARY KEY, nome_menu TEXT);
INSERT INTO i3geoadmin_menus VALUES('i3Geo','i3Geo','i3Geo English','SIM','','SIM','',1,'Teste');
INSERT INTO i3geoadmin_menus VALUES('Rede GeoPr','Rede GeoPr','GeoPr network','NAO','','NAO','',2,'Rede GeoPr');
INSERT INTO i3geoadmin_menus VALUES('LAG','LAG','LAG','NAO','','','teste',3,'LAG');
INSERT INTO i3geoadmin_menus VALUES('','','','NAO','','SIM','',4,'teste vazio');
CREATE TABLE i3geoadmin_n1 (publicado TEXT, ordem NUMERIC, id_menu NUMERIC, id_grupo NUMERIC, id_n1 INTEGER PRIMARY KEY, n1_perfil TEXT);
INSERT INTO i3geoadmin_n1 VALUES('SIM',NULL,1,24,1,'');
INSERT INTO i3geoadmin_n1 VALUES('NAO',1,1,2,2,'');
INSERT INTO i3geoadmin_n1 VALUES('NAO',NULL,2,3,3,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,2,4,4,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,2,5,5,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,2,6,6,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,7,7,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,8,8,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,9,9,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,10,10,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,11,11,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,12,12,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,13,13,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,14,14,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,15,15,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,16,16,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,17,17,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,18,18,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,19,19,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,20,20,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,21,21,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,22,22,'');
INSERT INTO i3geoadmin_n1 VALUES(NULL,NULL,3,23,23,'');
INSERT INTO i3geoadmin_n1 VALUES('SIM',2,1,25,24,'');
INSERT INTO i3geoadmin_n1 VALUES('NAO',2,1,26,25,'');
INSERT INTO i3geoadmin_n1 VALUES('SIM',3,1,27,26,'');
INSERT INTO i3geoadmin_n1 VALUES('SIM',4,1,28,27,'teste');
CREATE TABLE i3geoadmin_n2 (publicado TEXT, ordem NUMERIC, id_n1 NUMERIC, id_n2 INTEGER PRIMARY KEY, id_subgrupo NUMERIC, n2_perfil TEXT);
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,1,2,2,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,2,3,3,'');
INSERT INTO i3geoadmin_n2 VALUES('SIM',NULL,3,4,4,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,4,5,5,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,5,6,6,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,6,7,7,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,8,8,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,9,9,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,10,10,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,11,11,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,12,12,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,13,13,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,14,14,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,15,15,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,16,16,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,17,17,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,18,18,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,19,19,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,20,20,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,21,21,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,22,22,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,23,23,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,24,24,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,7,25,25,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,8,26,26,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,8,27,27,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,8,28,28,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,9,29,29,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,9,30,30,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,10,31,31,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,10,32,32,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,10,33,33,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,11,34,34,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,11,35,35,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,11,36,36,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,11,37,37,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,12,38,38,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,12,39,39,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,12,40,40,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,12,41,41,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,42,42,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,43,43,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,44,44,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,45,45,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,46,46,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,47,47,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,48,48,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,49,49,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,50,50,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,51,51,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,52,52,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,53,53,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,54,54,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,55,55,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,56,56,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,57,57,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,13,58,58,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,14,59,59,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,14,60,60,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,14,61,61,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,14,62,62,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,14,63,63,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,15,64,64,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,15,65,65,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,15,66,66,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,15,67,67,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,15,68,68,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,16,69,69,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,16,70,70,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,16,71,71,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,17,72,72,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,17,73,73,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,74,74,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,75,75,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,76,76,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,77,45,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,78,77,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,79,78,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,18,80,79,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,81,80,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,82,81,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,83,82,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,84,83,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,85,84,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,86,85,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,19,87,86,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,20,88,87,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,20,89,88,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,20,90,89,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,20,91,90,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,20,92,91,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,20,93,92,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,94,93,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,95,26,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,96,94,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,97,95,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,98,96,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,99,97,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,100,98,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,101,99,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,102,100,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,103,101,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,104,102,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,21,105,103,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,106,104,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,107,105,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,108,106,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,109,107,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,110,108,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,111,109,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,22,112,110,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,113,111,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,114,112,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,115,113,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,116,114,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,117,115,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,118,116,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,119,117,'');
INSERT INTO i3geoadmin_n2 VALUES(NULL,NULL,23,120,118,'');
INSERT INTO i3geoadmin_n2 VALUES('SIM',1,1,121,119,'');
INSERT INTO i3geoadmin_n2 VALUES('SIM',1,24,122,2,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,123,124,-9708,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,124,125,-9687,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,125,126,-9924,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,126,127,-9551,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,127,128,-9412,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,128,129,-9104,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,129,130,-9614,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,130,131,-9564,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,131,132,-9700,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,132,133,-9151,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,133,134,-9468,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,134,135,-9296,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',2,123,136,-9314,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,136,137,-9954,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,137,138,-9712,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,138,139,-9200,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,139,140,-9808,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,140,141,-9927,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,141,142,-9775,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,142,143,-9856,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,143,144,-9749,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,144,145,-9711,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,145,146,-9693,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,146,147,-9778,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,147,148,-9632,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,148,149,-9770,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,149,150,-9596,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,150,151,-9513,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,151,152,-9632,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',2,148,153,-9175,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,153,154,-9851,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,154,155,-9170,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,155,156,-9350,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,156,157,-9312,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,157,158,-9332,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,158,159,-9961,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,159,160,-9470,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,160,161,-9733,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,161,162,-9874,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,162,163,-9381,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,163,164,-9661,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,164,165,-9256,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,165,166,-9456,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,166,167,-9628,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,167,168,-9000,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,168,169,-9114,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,169,170,-9495,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,170,171,-9472,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,171,172,-9680,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,172,173,-9488,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,173,174,-9658,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,175,176,-9580,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,176,177,-9602,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,177,178,-9756,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,178,179,-9495,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',2,170,180,-9563,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,180,181,-9081,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,181,182,-9790,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,182,183,-9968,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,183,184,-9909,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,184,185,-9783,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,185,186,-9400,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,186,187,-9364,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,187,188,-9178,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,188,189,-9738,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,189,190,-9387,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,190,191,-9674,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,191,192,-9065,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,192,193,-9395,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,193,194,-9400,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',2,186,195,-9353,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,195,196,-9820,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,196,197,-9753,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,197,198,-9513,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',2,151,199,-9796,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,199,200,-9357,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,200,201,-9386,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,201,202,-9428,'');
INSERT INTO i3geoadmin_n2 VALUES('NAO',1,27,203,-9258,'');
CREATE TABLE i3geoadmin_n3 (publicado TEXT, ordem NUMERIC, id_n2 NUMERIC, id_n3 INTEGER PRIMARY KEY, id_tema NUMERIC, n3_perfil TEXT);
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,2,14,15,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,2,15,16,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,2,16,17,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,4,18,18,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,4,19,19,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,4,20,20,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,4,21,21,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,4,22,22,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,4,23,23,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,24,24,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,25,25,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,26,26,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,27,27,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,28,28,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,29,29,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,30,30,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,5,31,31,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,32,32,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,33,33,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,34,34,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,35,35,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,36,36,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,37,37,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,38,38,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,39,39,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,40,40,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,41,41,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,42,42,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,43,43,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,44,44,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,45,45,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,6,46,46,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,7,47,47,'');
INSERT INTO i3geoadmin_n3 VALUES(NULL,NULL,7,48,48,'');
INSERT INTO i3geoadmin_n3 VALUES('NAO',2,2,50,32,'');
INSERT INTO i3geoadmin_n3 VALUES('NAO',3,2,51,45,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',4,2,52,59,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',5,2,53,46,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',1,121,54,60,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',2,121,55,63,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',7,2,57,66,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',8,2,58,67,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',9,2,59,68,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',1,122,60,61,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',10,2,61,64,'');
INSERT INTO i3geoadmin_n3 VALUES('NAO',11,2,62,30,'');
INSERT INTO i3geoadmin_n3 VALUES('SIM',14,2,65,75,'');
CREATE TABLE i3geoadmin_operacoes (id_operacao INTEGER PRIMARY KEY, codigo TEXT, descricao TEXT);
INSERT INTO i3geoadmin_operacoes VALUES(1,'admin/html/editormapfile','editor de mapfiles do sistema de administracao');
INSERT INTO i3geoadmin_operacoes VALUES(2,'admin/html/operacoes','abre o editor de operacoes');
INSERT INTO i3geoadmin_operacoes VALUES(3,'teste/','teste');
INSERT INTO i3geoadmin_operacoes VALUES(4,'admin/html/arvore','edicao da arvore do catalogo de temas');
INSERT INTO i3geoadmin_operacoes VALUES(5,'admin/html/menus','edicao da lista de menus');
INSERT INTO i3geoadmin_operacoes VALUES(6,'admin/html/ogcws','edicao das preferencias do servico WMS');
INSERT INTO i3geoadmin_operacoes VALUES(7,'admin/html/atlas','edicao de atlas');
INSERT INTO i3geoadmin_operacoes VALUES(8,'admin/html/identifica','lista de sistemas incluidos na ferramenta de identificacao');
INSERT INTO i3geoadmin_operacoes VALUES(9,'admin/html/incluimap','adapta mapfiles antigos para versoes novas do Mapserver');
INSERT INTO i3geoadmin_operacoes VALUES(10,'admin/html/mapas','lista de links para mapas');
INSERT INTO i3geoadmin_operacoes VALUES(11,'admin/html/perfis','lista controlada de perfis');
INSERT INTO i3geoadmin_operacoes VALUES(12,'admin/html/sistemas','lista de sistemas complementares que sao mostrados no catalogo');
INSERT INTO i3geoadmin_operacoes VALUES(13,'admin/html/subirshapefile','upload de shapefile para uma pasta especifica no servidor');
INSERT INTO i3geoadmin_operacoes VALUES(14,'admin/html/tags','edicao da lista controlada de tags');
INSERT INTO i3geoadmin_operacoes VALUES(15,'admin/html/webservices','cadastro de links para webservices');
CREATE TABLE i3geoadmin_operacoespapeis (id_operacao NUMERIC, id_papel NUMERIC);
INSERT INTO i3geoadmin_operacoespapeis VALUES(1,2);
INSERT INTO i3geoadmin_operacoespapeis VALUES(1,3);
INSERT INTO i3geoadmin_operacoespapeis VALUES(4,3);
INSERT INTO i3geoadmin_operacoespapeis VALUES(5,3);
INSERT INTO i3geoadmin_operacoespapeis VALUES(7,3);
INSERT INTO i3geoadmin_operacoespapeis VALUES(10,3);
INSERT INTO i3geoadmin_operacoespapeis VALUES(13,2);
INSERT INTO i3geoadmin_operacoespapeis VALUES(13,4);
INSERT INTO i3geoadmin_operacoespapeis VALUES(15,3);
CREATE TABLE i3geoadmin_papeis (descricao TEXT, id_papel INTEGER PRIMARY KEY, nome TEXT);
INSERT INTO i3geoadmin_papeis VALUES('Podem executar qualquer tarefa, inclusive cadastrar novos administradores',1,'admin');
INSERT INTO i3geoadmin_papeis VALUES('Podem criar/editar qualquer tema (mapfile) mas nao podem editar a arvore do catalogo de temas',2,'editores');
INSERT INTO i3geoadmin_papeis VALUES('Podem alterar a arvore do catalogo e dos atlas',3,'publicadores');
INSERT INTO i3geoadmin_papeis VALUES('Podem editar dados geograficos',4,'editoresgeo');
CREATE TABLE i3geoadmin_papelusuario (id_papel NUMERIC, id_usuario NUMERIC);
INSERT INTO i3geoadmin_papelusuario VALUES(1,1);
INSERT INTO i3geoadmin_papelusuario VALUES(2,2);
INSERT INTO i3geoadmin_papelusuario VALUES(3,3);
INSERT INTO i3geoadmin_papelusuario VALUES(4,4);
CREATE TABLE i3geoadmin_perfis (id_perfil INTEGER PRIMARY KEY, perfil TEXT);
INSERT INTO i3geoadmin_perfis VALUES(1,'teste');
INSERT INTO i3geoadmin_perfis VALUES(2,'teste1');
CREATE TABLE i3geoadmin_raiz (ordem NUMERIC, id_tema NUMERIC, id_menu NUMERIC, id_nivel NUMERIC, id_raiz INTEGER PRIMARY KEY, nivel NUMERIC, perfil TEXT);
INSERT INTO i3geoadmin_raiz VALUES(NULL,1,1,0,1,0,'');
INSERT INTO i3geoadmin_raiz VALUES(1,14,1,1,2,1,'');
INSERT INTO i3geoadmin_raiz VALUES(1,61,1,24,3,1,'');
INSERT INTO i3geoadmin_raiz VALUES(1,17,1,0,4,0,'');
INSERT INTO i3geoadmin_raiz VALUES(1,35,1,25,5,1,'');
INSERT INTO i3geoadmin_raiz VALUES(1,59,1,26,6,1,'');
INSERT INTO i3geoadmin_raiz VALUES(2,72,1,1,7,1,'');
INSERT INTO i3geoadmin_raiz VALUES(3,77,1,1,8,1,'');
INSERT INTO i3geoadmin_raiz VALUES(2,NULL,1,0,9,0,'');
CREATE TABLE i3geoadmin_sistemas (publicado_sistema TEXT, id_sistema INTEGER PRIMARY KEY, nome_sistema TEXT, perfil_sistema TEXT);
INSERT INTO i3geoadmin_sistemas VALUES('NAO',1,'Planos de manejo Florestal (IBAMA)','');
CREATE TABLE i3geoadmin_sistemasf (abrir_funcao TEXT, h_funcao NUMERIC, id_funcao INTEGER PRIMARY KEY, id_sistema NUMERIC, nome_funcao TEXT, perfil_funcao TEXT, w_funcao NUMERIC);
INSERT INTO i3geoadmin_sistemasf VALUES('http://localhost/i3geo/ferramentas/planosmanejoflorestal/pesquisa.htm',300,1,1,'Pesquisar','',600);
CREATE TABLE i3geoadmin_subgrupos (it TEXT, es TEXT, en TEXT, desc_subgrupo TEXT, id_subgrupo INTEGER PRIMARY KEY, nome_subgrupo TEXT);
INSERT INTO i3geoadmin_subgrupos VALUES('Clima','Clima','Clima','',1,'Clima');
INSERT INTO i3geoadmin_subgrupos VALUES('Teste','Teste','Teste','',2,'Teste');
INSERT INTO i3geoadmin_subgrupos VALUES('Isto é só um exemplo. !!!!','Isto é só um exemplo. !!!!','Isto é só um exemplo. !!!!','',3,'Isto é só um exemplo. !!!!');
INSERT INTO i3geoadmin_subgrupos VALUES('ANEEL','ANEEL','ANEEL','',4,'ANEEL');
INSERT INTO i3geoadmin_subgrupos VALUES('OGC Web Services - DSA-INPE','OGC Web Services - DSA-INPE','OGC Web Services - DSA-INPE','',5,'OGC Web Services - DSA-INPE');
INSERT INTO i3geoadmin_subgrupos VALUES('OGC - SIPAM','OGC - SIPAM','OGC - SIPAM','',6,'OGC - SIPAM');
INSERT INTO i3geoadmin_subgrupos VALUES('Base topológica hídrica','Base topológica hídrica','Base topológica hídrica','',7,'Base topológica hídrica');
INSERT INTO i3geoadmin_subgrupos VALUES('Abastecimento','Abastecimento','Abastecimento','',8,'Abastecimento');
INSERT INTO i3geoadmin_subgrupos VALUES('Agricultura familiar','Agricultura familiar','Agricultura familiar','',9,'Agricultura familiar');
INSERT INTO i3geoadmin_subgrupos VALUES('Agricultura de subsistência','Agricultura de subsistência','Agricultura de subsistência','',10,'Agricultura de subsistência');
INSERT INTO i3geoadmin_subgrupos VALUES('Agricultura orgânica','Agricultura orgânica','Agricultura orgânica','',11,'Agricultura orgânica');
INSERT INTO i3geoadmin_subgrupos VALUES('Alimento','Alimento','Alimento','',12,'Alimento');
INSERT INTO i3geoadmin_subgrupos VALUES('Assistência técnica','Assistência técnica','Assistência técnica','',13,'Assistência técnica');
INSERT INTO i3geoadmin_subgrupos VALUES('Defesa Vegetal','Defesa Vegetal','Defesa Vegetal','',14,'Defesa Vegetal');
INSERT INTO i3geoadmin_subgrupos VALUES('Engenharia agrícola','Engenharia agrícola','Engenharia agrícola','',15,'Engenharia agrícola');
INSERT INTO i3geoadmin_subgrupos VALUES('Extensão rural','Extensão rural','Extensão rural','',16,'Extensão rural');
INSERT INTO i3geoadmin_subgrupos VALUES('Extrativismo','Extrativismo','Extrativismo','',17,'Extrativismo');
INSERT INTO i3geoadmin_subgrupos VALUES('Organização Agrária','Organização Agrária','Organização Agrária','',18,'Organização Agrária');
INSERT INTO i3geoadmin_subgrupos VALUES('Pecuária','Pecuária','Pecuária','',19,'Pecuária');
INSERT INTO i3geoadmin_subgrupos VALUES('Pesca','Pesca','Pesca','',20,'Pesca');
INSERT INTO i3geoadmin_subgrupos VALUES('Política agrícola','Política agrícola','Política agrícola','',21,'Política agrícola');
INSERT INTO i3geoadmin_subgrupos VALUES('Produção vegetal','Produção vegetal','Produção vegetal','',22,'Produção vegetal');
INSERT INTO i3geoadmin_subgrupos VALUES('Produto vegetal','Produto vegetal','Produto vegetal','',23,'Produto vegetal');
INSERT INTO i3geoadmin_subgrupos VALUES('Solos','Solos','Solos','',24,'Solos');
INSERT INTO i3geoadmin_subgrupos VALUES('Transgenia e seqüenciamento','Transgenia e seqüenciamento','Transgenia e seqüenciamento','',25,'Transgenia e seqüenciamento');
INSERT INTO i3geoadmin_subgrupos VALUES('Ciência e tecnologia','Ciência e tecnologia','Ciência e tecnologia','',26,'Ciência e tecnologia');
INSERT INTO i3geoadmin_subgrupos VALUES('Comunicação','Comunicação','Comunicação','',27,'Comunicação');
INSERT INTO i3geoadmin_subgrupos VALUES('Informação: Gestão, Preservação e Acesso','Informação: Gestão, Preservação e Acesso','Informação: Gestão, Preservação e Acesso','',28,'Informação: Gestão, Preservação e Acesso');
INSERT INTO i3geoadmin_subgrupos VALUES('Comércio e Serviços','Comércio e Serviços','Comércio e Serviços','',29,'Comércio e Serviços');
INSERT INTO i3geoadmin_subgrupos VALUES('Turismo','Turismo','Turismo','',30,'Turismo');
INSERT INTO i3geoadmin_subgrupos VALUES('Cultura','Cultura','Cultura','',31,'Cultura');
INSERT INTO i3geoadmin_subgrupos VALUES('Esporte','Esporte','Esporte','',32,'Esporte');
INSERT INTO i3geoadmin_subgrupos VALUES('Lazer','Lazer','Lazer','',33,'Lazer');
INSERT INTO i3geoadmin_subgrupos VALUES('Defesa Nacional','Defesa Nacional','Defesa Nacional','',34,'Defesa Nacional');
INSERT INTO i3geoadmin_subgrupos VALUES('Segurança Nacional','Segurança Nacional','Segurança Nacional','',35,'Segurança Nacional');
INSERT INTO i3geoadmin_subgrupos VALUES('Segurança pública','Segurança pública','Segurança pública','',36,'Segurança pública');
INSERT INTO i3geoadmin_subgrupos VALUES('Serviço de inteligência','Serviço de inteligência','Serviço de inteligência','',37,'Serviço de inteligência');
INSERT INTO i3geoadmin_subgrupos VALUES('Administração financeira','Administração financeira','Administração financeira','',38,'Administração financeira');
INSERT INTO i3geoadmin_subgrupos VALUES('Economia','Economia','Economia','',39,'Economia');
INSERT INTO i3geoadmin_subgrupos VALUES('Encargos financeiros','Encargos financeiros','Encargos financeiros','',40,'Encargos financeiros');
INSERT INTO i3geoadmin_subgrupos VALUES('Finanças','Finanças','Finanças','',41,'Finanças');
INSERT INTO i3geoadmin_subgrupos VALUES('Assistência ao estudante','Assistência ao estudante','Assistência ao estudante','',42,'Assistência ao estudante');
INSERT INTO i3geoadmin_subgrupos VALUES('Avaliação do sistema educacional','Avaliação do sistema educacional','Avaliação do sistema educacional','',43,'Avaliação do sistema educacional');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação a distância','Educação a distância','Educação a distância','',44,'Educação a distância');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação ambiental','Educação ambiental','Educação ambiental','',45,'Educação ambiental');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação básica','Educação básica','Educação básica','',46,'Educação básica');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação de jovens e adultos','Educação de jovens e adultos','Educação de jovens e adultos','',47,'Educação de jovens e adultos');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação do campo','Educação do campo','Educação do campo','',48,'Educação do campo');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação indígena','Educação indígena','Educação indígena','',49,'Educação indígena');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação para quilombolas','Educação para quilombolas','Educação para quilombolas','',50,'Educação para quilombolas');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação profissional e tecnológica','Educação profissional e tecnológica','Educação profissional e tecnológica','',51,'Educação profissional e tecnológica');
INSERT INTO i3geoadmin_subgrupos VALUES('Educação superior','Educação superior','Educação superior','',52,'Educação superior');
INSERT INTO i3geoadmin_subgrupos VALUES('Financiamento da educação','Financiamento da educação','Financiamento da educação','',53,'Financiamento da educação');
INSERT INTO i3geoadmin_subgrupos VALUES('Gestão escolar','Gestão escolar','Gestão escolar','',54,'Gestão escolar');
INSERT INTO i3geoadmin_subgrupos VALUES('Legislação educacional','Legislação educacional','Legislação educacional','',55,'Legislação educacional');
INSERT INTO i3geoadmin_subgrupos VALUES('Métodos e meios de ensino e aprendizagem','Métodos e meios de ensino e aprendizagem','Métodos e meios de ensino e aprendizagem','',56,'Métodos e meios de ensino e aprendizagem');
INSERT INTO i3geoadmin_subgrupos VALUES('Parâmetros e diretrizes curriculares nacionais','Parâmetros e diretrizes curriculares nacionais','Parâmetros e diretrizes curriculares nacionais','',57,'Parâmetros e diretrizes curriculares nacionais');
INSERT INTO i3geoadmin_subgrupos VALUES('Profissionais da educação','Profissionais da educação','Profissionais da educação','',58,'Profissionais da educação');
INSERT INTO i3geoadmin_subgrupos VALUES('Administração Pública','Administração Pública','Administração Pública','',59,'Administração Pública');
INSERT INTO i3geoadmin_subgrupos VALUES('Fiscalização do Estado','Fiscalização do Estado','Fiscalização do Estado','',60,'Fiscalização do Estado');
INSERT INTO i3geoadmin_subgrupos VALUES('Governo Eletrônico','Governo Eletrônico','Governo Eletrônico','',61,'Governo Eletrônico');
INSERT INTO i3geoadmin_subgrupos VALUES('Organização do estado','Organização do estado','Organização do estado','',62,'Organização do estado');
INSERT INTO i3geoadmin_subgrupos VALUES('Política','Política','Política','',63,'Política');
INSERT INTO i3geoadmin_subgrupos VALUES('Habitação','Habitação','Habitação','',64,'Habitação');
INSERT INTO i3geoadmin_subgrupos VALUES('Planejamento urbano','Planejamento urbano','Planejamento urbano','',65,'Planejamento urbano');
INSERT INTO i3geoadmin_subgrupos VALUES('Saneamento','Saneamento','Saneamento','',66,'Saneamento');
INSERT INTO i3geoadmin_subgrupos VALUES('Serviços Urbanos','Serviços Urbanos','Serviços Urbanos','',67,'Serviços Urbanos');
INSERT INTO i3geoadmin_subgrupos VALUES('Urbanismo','Urbanismo','Urbanismo','',68,'Urbanismo');
INSERT INTO i3geoadmin_subgrupos VALUES('Política e gestão industrial','Política e gestão industrial','Política e gestão industrial','',69,'Política e gestão industrial');
INSERT INTO i3geoadmin_subgrupos VALUES('Produção industrial','Produção industrial','Produção industrial','',70,'Produção industrial');
INSERT INTO i3geoadmin_subgrupos VALUES('Recursos energéticos','Recursos energéticos','Recursos energéticos','',71,'Recursos energéticos');
INSERT INTO i3geoadmin_subgrupos VALUES('Justiça','Justiça','Justiça','',72,'Justiça');
INSERT INTO i3geoadmin_subgrupos VALUES('Legislação e Jurisprudência','Legislação e Jurisprudência','Legislação e Jurisprudência','',73,'Legislação e Jurisprudência');
INSERT INTO i3geoadmin_subgrupos VALUES('Áreas Protegidas (Parques, Unidades de conservação)','Áreas Protegidas (Parques, Unidades de conservação)','Áreas Protegidas (Parques, Unidades de conservação)','',74,'Áreas Protegidas (Parques, Unidades de conservação)');
INSERT INTO i3geoadmin_subgrupos VALUES('Biodiversidade','Biodiversidade','Biodiversidade','',75,'Biodiversidade');
INSERT INTO i3geoadmin_subgrupos VALUES('Desenvolvimento sustentável','Desenvolvimento sustentável','Desenvolvimento sustentável','',76,'Desenvolvimento sustentável');
INSERT INTO i3geoadmin_subgrupos VALUES('Fenômenos naturais','Fenômenos naturais','Fenômenos naturais','',77,'Fenômenos naturais');
INSERT INTO i3geoadmin_subgrupos VALUES('Gestão do meio ambiente','Gestão do meio ambiente','Gestão do meio ambiente','',78,'Gestão do meio ambiente');
INSERT INTO i3geoadmin_subgrupos VALUES('Recursos naturais','Recursos naturais','Recursos naturais','',79,'Recursos naturais');
INSERT INTO i3geoadmin_subgrupos VALUES('Assistência e Desenvolvimento Social','Assistência e Desenvolvimento Social','Assistência e Desenvolvimento Social','',80,'Assistência e Desenvolvimento Social');
INSERT INTO i3geoadmin_subgrupos VALUES('Comunidade e Sociedade','Comunidade e Sociedade','Comunidade e Sociedade','',81,'Comunidade e Sociedade');
INSERT INTO i3geoadmin_subgrupos VALUES('Família','Família','Família','',82,'Família');
INSERT INTO i3geoadmin_subgrupos VALUES('Organização e Participação da Sociedade Civil','Organização e Participação da Sociedade Civil','Organização e Participação da Sociedade Civil','',83,'Organização e Participação da Sociedade Civil');
INSERT INTO i3geoadmin_subgrupos VALUES('Pessoa','Pessoa','Pessoa','',84,'Pessoa');
INSERT INTO i3geoadmin_subgrupos VALUES('Previdência Social','Previdência Social','Previdência Social','',85,'Previdência Social');
INSERT INTO i3geoadmin_subgrupos VALUES('Proteção e defesa do cidadão','Proteção e defesa do cidadão','Proteção e defesa do cidadão','',86,'Proteção e defesa do cidadão');
INSERT INTO i3geoadmin_subgrupos VALUES('Estrangeiro','Estrangeiro','Estrangeiro','',87,'Estrangeiro');
INSERT INTO i3geoadmin_subgrupos VALUES('Organizações internacionais','Organizações internacionais','Organizações internacionais','',88,'Organizações internacionais');
INSERT INTO i3geoadmin_subgrupos VALUES('Política externa','Política externa','Política externa','',89,'Política externa');
INSERT INTO i3geoadmin_subgrupos VALUES('Promoção comercial','Promoção comercial','Promoção comercial','',90,'Promoção comercial');
INSERT INTO i3geoadmin_subgrupos VALUES('Relações diplomáticas','Relações diplomáticas','Relações diplomáticas','',91,'Relações diplomáticas');
INSERT INTO i3geoadmin_subgrupos VALUES('Serviços consulares','Serviços consulares','Serviços consulares','',92,'Serviços consulares');
INSERT INTO i3geoadmin_subgrupos VALUES('Auditoria','Auditoria','Auditoria','',93,'Auditoria');
INSERT INTO i3geoadmin_subgrupos VALUES('Ética de profissionais de saúde','Ética de profissionais de saúde','Ética de profissionais de saúde','',94,'Ética de profissionais de saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Legislação','Legislação','Legislação','',95,'Legislação');
INSERT INTO i3geoadmin_subgrupos VALUES('Orçamento','Orçamento','Orçamento','',96,'Orçamento');
INSERT INTO i3geoadmin_subgrupos VALUES('Participação e Controle Social','Participação e Controle Social','Participação e Controle Social','',97,'Participação e Controle Social');
INSERT INTO i3geoadmin_subgrupos VALUES('Promoção da Saúde','Promoção da Saúde','Promoção da Saúde','',98,'Promoção da Saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Proteção da saúde','Proteção da saúde','Proteção da saúde','',99,'Proteção da saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Recuperação da Saúde','Recuperação da Saúde','Recuperação da Saúde','',100,'Recuperação da Saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Recursos humanos em saúde','Recursos humanos em saúde','Recursos humanos em saúde','',101,'Recursos humanos em saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Sistema de informação em saúde','Sistema de informação em saúde','Sistema de informação em saúde','',102,'Sistema de informação em saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Sistema de Saúde','Sistema de Saúde','Sistema de Saúde','',103,'Sistema de Saúde');
INSERT INTO i3geoadmin_subgrupos VALUES('Fiscalização do trabalho','Fiscalização do trabalho','Fiscalização do trabalho','',104,'Fiscalização do trabalho');
INSERT INTO i3geoadmin_subgrupos VALUES('Legislação trabalhista','Legislação trabalhista','Legislação trabalhista','',105,'Legislação trabalhista');
INSERT INTO i3geoadmin_subgrupos VALUES('Mercado de trabalho','Mercado de trabalho','Mercado de trabalho','',106,'Mercado de trabalho');
INSERT INTO i3geoadmin_subgrupos VALUES('Política trabalhista','Política trabalhista','Política trabalhista','',107,'Política trabalhista');
INSERT INTO i3geoadmin_subgrupos VALUES('Profissões e ocupações','Profissões e ocupações','Profissões e ocupações','',108,'Profissões e ocupações');
INSERT INTO i3geoadmin_subgrupos VALUES('Qualificação e aprendizagem profissional','Qualificação e aprendizagem profissional','Qualificação e aprendizagem profissional','',109,'Qualificação e aprendizagem profissional');
INSERT INTO i3geoadmin_subgrupos VALUES('Trabalho estrangeiro','Trabalho estrangeiro','Trabalho estrangeiro','',110,'Trabalho estrangeiro');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte aéreo','Transporte aéreo','Transporte aéreo','',111,'Transporte aéreo');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte aquaviário (hidroviário)','Transporte aquaviário (hidroviário)','Transporte aquaviário (hidroviário)','',112,'Transporte aquaviário (hidroviário)');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte dutoviário','Transporte dutoviário','Transporte dutoviário','',113,'Transporte dutoviário');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte ferroviário','Transporte ferroviário','Transporte ferroviário','',114,'Transporte ferroviário');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte internacional','Transporte internacional','Transporte internacional','',115,'Transporte internacional');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte multimodal','Transporte multimodal','Transporte multimodal','',116,'Transporte multimodal');
INSERT INTO i3geoadmin_subgrupos VALUES('Transporte rodoviário','Transporte rodoviário','Transporte rodoviário','',117,'Transporte rodoviário');
INSERT INTO i3geoadmin_subgrupos VALUES('Transportes especiais','Transportes especiais','Transportes especiais','',118,'Transportes especiais');
INSERT INTO i3geoadmin_subgrupos VALUES('Teste de imagem','Teste de imagem','Image test','',119,'Teste de imagem');
INSERT INTO i3geoadmin_subgrupos VALUES('','','','',120,'teste de nome de subgrupo');
CREATE TABLE i3geoadmin_tags (id_tag INTEGER PRIMARY KEY, nome TEXT);
INSERT INTO i3geoadmin_tags VALUES(1,'clima');
INSERT INTO i3geoadmin_tags VALUES(2,'tempo');
INSERT INTO i3geoadmin_tags VALUES(3,'nuvens');
INSERT INTO i3geoadmin_tags VALUES(4,'previsão');
INSERT INTO i3geoadmin_tags VALUES(5,'temperatura');
INSERT INTO i3geoadmin_tags VALUES(6,'chuva');
INSERT INTO i3geoadmin_tags VALUES(7,'pressão');
INSERT INTO i3geoadmin_tags VALUES(8,'evaporação');
INSERT INTO i3geoadmin_tags VALUES(9,'oceano');
INSERT INTO i3geoadmin_tags VALUES(10,'terra');
INSERT INTO i3geoadmin_tags VALUES(11,'satélite');
INSERT INTO i3geoadmin_tags VALUES(12,'bioma');
INSERT INTO i3geoadmin_tags VALUES(13,'vegetação');
INSERT INTO i3geoadmin_tags VALUES(14,'biodiversidade');
INSERT INTO i3geoadmin_tags VALUES(15,'reservatório');
INSERT INTO i3geoadmin_tags VALUES(16,'água');
INSERT INTO i3geoadmin_tags VALUES(17,'energia');
INSERT INTO i3geoadmin_tags VALUES(18,'linhão');
INSERT INTO i3geoadmin_tags VALUES(19,'eólica');
INSERT INTO i3geoadmin_tags VALUES(20,'térmica');
INSERT INTO i3geoadmin_tags VALUES(21,'hidrelétrica');
INSERT INTO i3geoadmin_tags VALUES(22,'subestação');
INSERT INTO i3geoadmin_tags VALUES(23,'imagem');
INSERT INTO i3geoadmin_tags VALUES(24,'goes');
INSERT INTO i3geoadmin_tags VALUES(25,'risco');
INSERT INTO i3geoadmin_tags VALUES(26,'fogo');
INSERT INTO i3geoadmin_tags VALUES(27,'calor');
INSERT INTO i3geoadmin_tags VALUES(28,'queimada');
INSERT INTO i3geoadmin_tags VALUES(29,'aeroporto');
INSERT INTO i3geoadmin_tags VALUES(30,'desmatamento');
INSERT INTO i3geoadmin_tags VALUES(31,'localidade');
INSERT INTO i3geoadmin_tags VALUES(32,'estação');
INSERT INTO i3geoadmin_tags VALUES(33,'meteorológica');
INSERT INTO i3geoadmin_tags VALUES(34,'vsat');
INSERT INTO i3geoadmin_tags VALUES(35,'raios');
INSERT INTO i3geoadmin_tags VALUES(36,'solos');
INSERT INTO i3geoadmin_tags VALUES(37,'rio');
INSERT INTO i3geoadmin_tags VALUES(38,'bacia');
INSERT INTO i3geoadmin_tags VALUES(39,'vegetaÃ§Ã£o');
INSERT INTO i3geoadmin_tags VALUES(40,'');
INSERT INTO i3geoadmin_tags VALUES(41,'null');
INSERT INTO i3geoadmin_tags VALUES(42,'teste');
INSERT INTO i3geoadmin_tags VALUES(43,'shp');
CREATE TABLE i3geoadmin_temas (it TEXT, es TEXT, en TEXT, kmz_tema TEXT, id_tema INTEGER PRIMARY KEY, kml_tema , ogc_tema , download_tema , tags_tema , tipoa_tema , link_tema , desc_tema , nome_tema , codigo_tema );
INSERT INTO i3geoadmin_temas VALUES('Cartografia básica (raster)','Cartografia básica (raster)','Cartografia básica (raster)',NULL,1,'nao','nao','nao','clima tempo','WMS','http://mapas.mma.gov.br/i3geo/wscliente.htm','Web service com a cartografia básica','Cartografia básica (raster)','cartobase');
INSERT INTO i3geoadmin_temas VALUES('Biomas para teste de erros','Biomas para teste de erros','Error tests from Biomas',NULL,14,'SIM','SIM','SIM','','','http://mapas.mma.gov.br','','Biomas para teste de erros','biomaerro');
INSERT INTO i3geoadmin_temas VALUES('Teste de inclusao de tema PHP','Teste de inclusao de tema PHP','Teste de inclusao de tema PHP','',15,'','','','','','','','Teste de inclusao de tema PHP','testephp');
INSERT INTO i3geoadmin_temas VALUES('Teste de zoom','Teste de zoom','Teste de zoom',NULL,16,'NAO','NAO','NAO','','','','','Teste de zoom','testezoom');
INSERT INTO i3geoadmin_temas VALUES('Teste de autoclasses','Teste de autoclasses','Teste de autoclasses',NULL,17,'','SIM','','','','','','Teste de autoclasses','autolegenda_exemplo');
INSERT INTO i3geoadmin_temas VALUES('Reservatórios','Reservatórios','Reservatórios',NULL,18,'','','','reservatório água energia','WMS','http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/gsiwms?service=wms&request=getcapabilities&version=1.1.1','','Reservatórios','geopr_aneel_reservatorios');
INSERT INTO i3geoadmin_temas VALUES('Linhas de transmissão','Linhas de transmissão','Linhas de transmissão',NULL,19,'','','','energia linhão','WMS','http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/gsiwms?service=wms&request=getcapabilities&version=1.1.1','','Linhas de transmissão','geopr_aneel_linhas');
INSERT INTO i3geoadmin_temas VALUES('Usinas eólicas','Usinas eólicas','Usinas eólicas',NULL,20,'','','','energia eólica','WMS','http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/gsiwms?service=wms&request=getcapabilities&version=1.1.1','','Usinas eólicas','geopr_aneel_eolicas');
INSERT INTO i3geoadmin_temas VALUES('Usinas termel�tricas','Usinas termel�tricas','Usinas termel�tricas','',21,'','','NAO','energia térmica','','http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/gsiwms?service=wms','','Usinas termelétricas','geopr_aneel_termeletricas');
INSERT INTO i3geoadmin_temas VALUES('Aproveitamentos hidrelétricos','Aproveitamentos hidrelétricos','Aproveitamentos hidrelétricos',NULL,22,'','','','energia hidrelétrica','WMS','http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/gsiwms?service=wms&request=getcapabilities&version=1.1.1','','Aproveitamentos hidrelétricos','geopr_aneel_aproveitamentos');
INSERT INTO i3geoadmin_temas VALUES('Sub-estações','Sub-estações','Sub-estações',NULL,23,'','','','energia subestação','WMS','http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/gsiwms?service=wms&request=getcapabilities&version=1.1.1','','Sub-estações','geopr_aneel_subestacoes');
INSERT INTO i3geoadmin_temas VALUES('Fortracc - Previsão 120 minutos','Fortracc - Previsão 120 minutos','Fortracc - Previsão 120 minutos',NULL,24,'','','','tempo previsão','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','','Fortracc - Previsão 120 minutos','geopr_dsainpe_fortracc120');
INSERT INTO i3geoadmin_temas VALUES('Fortracc - Estimativa de Chuva Atual','Fortracc - Estimativa de Chuva Atual','Fortracc - Estimativa de Chuva Atual',NULL,25,'','','','tempo previsão chuva','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','','Fortracc - Estimativa de Chuva Atual','geopr_dsainpe_fortrac');
INSERT INTO i3geoadmin_temas VALUES('Imagem GOES 10','Imagem GOES 10','Imagem GOES 10',NULL,26,'','','','imagem goes satélite','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','','Imagem GOES 10','geopr_dsainpe_goes10');
INSERT INTO i3geoadmin_temas VALUES('Mapa de Risco de Fogo- GOES-12','Mapa de Risco de Fogo- GOES-12','Mapa de Risco de Fogo- GOES-12',NULL,27,'','','','risco fogo goes','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','Mapa de Risco de ocorrência de fogo produzido diariamente para toda a extensão geográfica de cobertura das imagens do satélite GOES-12','Mapa de Risco de Fogo- GOES-12','geopr_dsainpe_mrg12');
INSERT INTO i3geoadmin_temas VALUES('Mapa de Risco - Previsão 1 dia','Mapa de Risco - Previsão 1 dia','Mapa de Risco - Previsão 1 dia',NULL,28,'','','','previsão fogo risco','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','Previsão do Mapa de Risco de Fogo gerado para amanha, com o Modelo Regional ETA-Climatológico, dados observacionais e Imagens do Satelite GOES-12.','Mapa de Risco - Previsão 1 dia','geopr_dsainpe_mrp1');
INSERT INTO i3geoadmin_temas VALUES('Precipitação Instantânea','Precipitação Instantânea','Precipitação Instantânea',NULL,29,'','','','tempo chuva','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','Dados de estimativa de precipiatação obtidos apartir de imagens GOES-10.','Precipitação Instantânea','geopr_dsainpe_prec_inst');
INSERT INTO i3geoadmin_temas VALUES('Focos queimada','Focos queimada','Focos queimada',NULL,30,'','','','calor queimada','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','Todos os focos de Queimadas de hoje e ontem.','Focos queimada','geopr_dsainpe_focos_2dias');
INSERT INTO i3geoadmin_temas VALUES('Focos queimada acumulados no mês','Focos queimada acumulados no mês','Focos queimada acumulados no mês',NULL,31,'','','','calor queimada','WMS','http://moingatu.cptec.inpe.br/cgi-bin/mapserv?map=/extra/www/html/webservice/ogc_fm.map&service=wms&request=getcapabilities&version=1.1.1','Todos os focos de Queimadas desde o início do mês até a data atual.','Focos queimada acumulados no mês','geopr_dsainpe_focos_acumulado');
INSERT INTO i3geoadmin_temas VALUES('Aeroportos e pistas de pouso','Aeroportos e pistas de pouso','Aeroportos e pistas de pouso',NULL,32,'','','','aeroporto','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Aeroportos e pistas de pouso','geopr_sipam_aeroportos');
INSERT INTO i3geoadmin_temas VALUES('Arco do desmatamento','Arco do desmatamento','Arco do desmatamento',NULL,33,'','','','desmatamento','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Arco do desmatamento','geopr_sipam_arco');
INSERT INTO i3geoadmin_temas VALUES('Localizacao das cidades, vilas e capitais na Amazonia','Localizacao das cidades, vilas e capitais na Amazonia','Localizacao das cidades, vilas e capitais na Amazonia',NULL,34,'','','','localidade','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Localizacao das cidades, vilas e capitais na Amazonia','geopr_sipam_localidades');
INSERT INTO i3geoadmin_temas VALUES('EMS - Estação metereológica de superfície','EMS - Estação metereológica de superfície','EMS - Estação metereológica de superfície',NULL,35,'','','','estação meteorológica','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','EMS - Estação metereológica de superfície','geopr_sipam_ems');
INSERT INTO i3geoadmin_temas VALUES('Estações VSAT','Estações VSAT','Estações VSAT',NULL,36,'','','','vsat','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Estações VSAT','geopr_sipam_vsat');
INSERT INTO i3geoadmin_temas VALUES('Estações de detecção de raios','Estações de detecção de raios','Estações de detecção de raios',NULL,37,'','','','raios','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Estações de detecção de raios','geopr_sipam_raios');
INSERT INTO i3geoadmin_temas VALUES('Estações de de superfície - Operacional','Estações de de superfície - Operacional','Estações de de superfície - Operacional',NULL,38,'','','','','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Estações de de superfície - Operacional','geopr_sipam_eso');
INSERT INTO i3geoadmin_temas VALUES('Área de cobertura - Goes','Área de cobertura - Goes','Área de cobertura - Goes',NULL,39,'','','','goes','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Área de cobertura - Goes','geopr_sipam_goes');
INSERT INTO i3geoadmin_temas VALUES('Localização HF DF','Localização HF DF','Localização HF DF',NULL,40,'','','','','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Localização HF DF','geopr_sipam_hfdf');
INSERT INTO i3geoadmin_temas VALUES('PCDs','PCDs','PCDs',NULL,41,'','','','','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','PCDs','geopr_sipam_pcds');
INSERT INTO i3geoadmin_temas VALUES('Radares metereológicos','Radares metereológicos','Radares metereológicos',NULL,42,'','','','','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Radares metereológicos','geopr_sipam_radarm');
INSERT INTO i3geoadmin_temas VALUES('Localização Tiros','Localização Tiros','Localização Tiros',NULL,43,'','','','','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Localização Tiros','geopr_sipam_tiros');
INSERT INTO i3geoadmin_temas VALUES('Classes de solos','Classes de solos','Classes de solos',NULL,44,'','','','solos','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Classes de solos','geopr_sipam_solospo');
INSERT INTO i3geoadmin_temas VALUES('Amostragem de solos','Amostragem de solos','Amostragem de solos',NULL,45,'','','','solos','WMS','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS&request=getcapabilities&version=1.1.1','','Amostragem de solos','geopr_sipam_solospt');
INSERT INTO i3geoadmin_temas VALUES('Vegetação WMS','Vegetação WMS','Vegetação WMS','',46,'','','','vegetação','','http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS','','Vegetação WMS','geopr_sipam_vege');
INSERT INTO i3geoadmin_temas VALUES('Região Hidrográfica Nível 1','Região Hidrográfica Nível 1','Região Hidrográfica Nível 1',NULL,47,'','','','rio','WMS','http://200.140.135.184/cgi-bin/mapserv?map=/usr/local/www/apache22/data/hidro/wshidro.map&request=getcapabilities&version=1.1.1&service=wms','','Região Hidrográfica Nível 1','geopr_ana_reghidro1');
INSERT INTO i3geoadmin_temas VALUES('Micro-bacias','Micro-bacias','Micro-bacias',NULL,48,'','','','bacia','WMS','http://200.140.135.184/cgi-bin/mapserv?map=/usr/local/www/apache22/data/hidro/wshidro.map&request=getcapabilities&version=1.1.1&service=wms','','Micro-bacias','geopr_ana_microbacias');
INSERT INTO i3geoadmin_temas VALUES('','','','',49,'SIM','SIM','SIM','','','','','Atlas biomasx','atlas_biomas');
INSERT INTO i3geoadmin_temas VALUES('Biomas shapefile','Biomas shapefile','Biomas shapefile','SIM',59,'SIM','','SIM','bioma teste shp','','http://mapas.mma.gov.br/geonetwork','isso é um teste de descrição','Biomas shapefile','biomashp');
INSERT INTO i3geoadmin_temas VALUES('Imagem CBERS','Imagem CBERS','Imagem CBERS',NULL,60,'SIM','SIM','SIM','','','','','Imagem CBERS','cbersgeo');
INSERT INTO i3geoadmin_temas VALUES('Teste UTF8 Postgis','Teste UTF8 Postgis','Teste UTF8 Postgis','',61,'SIM','SIM','SIM','vegetação','','','','Teste UTF8 Postgis','testeutf8postgis');
INSERT INTO i3geoadmin_temas VALUES('biomacon','biomacon','biomacon',NULL,62,'SIM','SIM','SIM','',NULL,'','','biomacon','biomacon');
INSERT INTO i3geoadmin_temas VALUES('Palete de cores','Palete de cores','Palete de cores',NULL,63,'SIM','SIM','SIM','','','','','Palete de cores','cinzapalete');
INSERT INTO i3geoadmin_temas VALUES('teste de template kml','teste de template kml','teste de template kml','SIM',64,'SIM','SIM','SIM','','','','','teste de template kml','testepttemplatekml');
INSERT INTO i3geoadmin_temas VALUES('bing','bing','bing',NULL,65,'SIM','SIM','SIM','',NULL,'','','bing','bing');
INSERT INTO i3geoadmin_temas VALUES('Teste de substituição de string','Teste de substituição de string','Teste de substituição de string','SIM',66,'SIM','SIM','SIM','','','','','Teste de substituição de string','testesubsstring');
INSERT INTO i3geoadmin_temas VALUES('Teste de projeção utm','Teste de projeção utm','Teste de projeção utm','',67,'','','','','','','','Teste de projeção utm','testeutm');
INSERT INTO i3geoadmin_temas VALUES('Vegetação shapefile','Vegetação shapefile','Vegetação shapefile','NAO',68,'SIM','SIM','SIM','','','','','Vegetação shapefile','vegetacao');
INSERT INTO i3geoadmin_temas VALUES('atlas_ucse','atlas_ucse','atlas_ucse','NAO',69,'SIM','SIM','SIM','',NULL,'','','atlas_ucse','atlas_ucse');
INSERT INTO i3geoadmin_temas VALUES('testepttemplatekml','testepttemplatekml','testepttemplatekml','NAO',70,'SIM','SIM','SIM','',NULL,'','','testepttemplatekml','testepttemplatekml');
INSERT INTO i3geoadmin_temas VALUES('','','','',71,'','','','','','','','teste criando novo mapfile','teste5');
INSERT INTO i3geoadmin_temas VALUES('Localidades','Localidades','Localidades','SIM',72,'SIM','','','','','','','Localidades','locali');
INSERT INTO i3geoadmin_temas VALUES('','','','NAO',73,'SIM','SIM','NAO','','','','','geopr_ana_federais','geopr_ana_federais');
INSERT INTO i3geoadmin_temas VALUES(NULL,NULL,NULL,'NAO',74,'SIM','SIM','SIM','',NULL,'','','p2r2uf1','p2r2uf1');
INSERT INTO i3geoadmin_temas VALUES('Povoado','Povoado','Povoado','SIM',75,'SIM','','SIM','','','','','Povoado','povoado');
INSERT INTO i3geoadmin_temas VALUES('Acid Mapsx','Acid Mapsx','Acid Mapsx','NAO',76,'SIM','SIM','SIM','','','teste','','Acid Maps','acidmap');
INSERT INTO i3geoadmin_temas VALUES(NULL,NULL,NULL,'NAO',77,'NAO','NAO','NAO','','','','','SLD - Teste de aplicação automática de SLD','biomashpwms');
INSERT INTO i3geoadmin_temas VALUES('','','','NAO',78,'SIM','SIM','SIM','','','','','biomapg x','biomapg');
CREATE TABLE i3geoadmin_usuarios (ativo NUMERIC, data_cadastro TEXT, email TEXT, id_usuario INTEGER PRIMARY KEY, login TEXT, nome_usuario TEXT, senha TEXT);
INSERT INTO i3geoadmin_usuarios VALUES(1,NULL,NULL,1,'admin','administrador do i3geo','admin');
INSERT INTO i3geoadmin_usuarios VALUES(1,NULL,NULL,2,'editor','teste de editor','editor');
INSERT INTO i3geoadmin_usuarios VALUES(1,NULL,NULL,3,'publicador','teste de publicador','publicador');
INSERT INTO i3geoadmin_usuarios VALUES(1,NULL,NULL,4,'editorgeo','teste de editor geo','editorgeo');
CREATE TABLE i3geoadmin_ws (nacessosok NUMERIC, nacessos NUMERIC, autor_ws TEXT, desc_ws TEXT, id_ws INTEGER PRIMARY KEY, link_ws TEXT, nome_ws TEXT, tipo_ws TEXT);
INSERT INTO i3geoadmin_ws VALUES(3,3,'MMA','Gerador automático de web services do I3Geo',2,'http://mapas.mma.gov.br/i3geo/ogc.php?','i3Geo MMA - Ministério do Meio Ambiente Brasil','WMS');
INSERT INTO i3geoadmin_ws VALUES(5,6,'Servidor do MMA','',6,'http://mapas.mma.gov.br/cgi-bin/mapserv?map=/opt/www/html/webservices/baseraster.map&','Base cartográfica raster do CIGEX','WMS');
INSERT INTO i3geoadmin_ws VALUES(53,54,'MMA','Biomas, áreas prioritárias',7,'http://mapas.mma.gov.br/cgi-bin/mapserv?map=/opt/www/html/webservices/biorregioes.map&','Biorregiões','WMS');
INSERT INTO i3geoadmin_ws VALUES(1,1,'MMA','',8,'http://mapas.mma.gov.br/cgi-bin/mapserv?map=/opt/www/html/webservices/florestaspublicas.map&','Florestas públicas','WMS');
INSERT INTO i3geoadmin_ws VALUES(NULL,NULL,'MMA','',10,'http://mapas.mma.gov.br/cgi-bin/mapserv?map=/opt/www/html/webservices/ucs.map&','Unidades de conservação federais do Brasil','WMS');
INSERT INTO i3geoadmin_ws VALUES(27,27,'DSA-INPE','',12,'http://pirandira.cptec.inpe.br/cgi-bin/mapserv?map=/extra2/sigma/www/webservice/webservice_dsa.map&','DSA-INPE','WMS');
INSERT INTO i3geoadmin_ws VALUES(1,1,'SIPAM','',14,'http://www2.sipam.gov.br:80/geoserver/wms?SERVICE=WMS','Sistema de Protecao da Amazonia','WMS');
INSERT INTO i3geoadmin_ws VALUES(11,15,'ANEEL','ANEEL - Agéncia Nacional de Energia Elétrica',15,'http://sigel.aneel.gov.br/wmsconnector/com.esri.wms.Esrimap/sigel_wms?','ANEEL - Agência Nacional de Energia Elétrica','WMS');
INSERT INTO i3geoadmin_ws VALUES(44,45,'ANA','',16,'http://200.140.135.184/cgi-bin/mapserv?map=/usr/local/www/apache22/data/hidro/wshidro.map&','Agência Nacional das Águas','WMS');
INSERT INTO i3geoadmin_ws VALUES(2,3,'INCRA','Assentamentos do INCRA',17,'http://acervofundiario.incra.gov.br/cgi-bin/mapserv.exe?map=e:/wmsincra/incra.map','Assentamentos INCRA','WMS');
INSERT INTO i3geoadmin_ws VALUES(NULL,NULL,'EMBRAPA','Imagens de satélite',21,'http://www.cnpm.embrapa.br/cgi-bin/wmsService?','Imagens Embrapa','WMS');
INSERT INTO i3geoadmin_ws VALUES(1,2,'JPL','',25,'http://wms.jpl.nasa.gov/wms.cgi?','Mosaico Landsat - JPL World Map Service','WMS');
INSERT INTO i3geoadmin_ws VALUES(1,4,'FAO','',28,'http://geonetwork3.fao.org/ows/12743?','Aridity index','WMS');
INSERT INTO i3geoadmin_ws VALUES(0,2,'FAO','',35,'http://geonetwork3.fao.org/ows/12757?','FAO - world protected areas','WMS');
INSERT INTO i3geoadmin_ws VALUES(NULL,NULL,'','',69,'http://ws.geonames.org/rssToGeoRSS?feedUrl=http://feeds.reuters.com/reuters/worldNews','Reuters: International','GEORSS');
INSERT INTO i3geoadmin_ws VALUES(NULL,NULL,'Panoramio','',70,'http://www.panoramio.com/kml?all','Fotos do Panoramio','KML');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','datadownload',71,'http://mapas.mma.gov.br/i3geo/datadownload.htm','MMA','DOWNLOAD');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','download',72,'http://www.ibge.gov.br/home/mapa_site/mapa_site.php','IBGE','DOWNLOAD');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','',73,'http://gmaps-samples.googlecode.com/svn/trunk/ggeoxml/cta.kml','Teste KML','KML');
INSERT INTO i3geoadmin_ws VALUES(0,0,'IBGE','',74,'http://localhost/i3geo/aplicmap/dados/Cidades_do_Brasil_2008.kmz','Cidades do Brasil - IBGE (KMZ)','KML');
INSERT INTO i3geoadmin_ws VALUES(0,0,'CPRM','',75,'http://geobank.sa.cprm.gov.br/cgi-bin/wmsserver/wms1000K?','Mapas geológicos e geoambientais','WMS');
INSERT INTO i3geoadmin_ws VALUES(0,0,'CPRM','',76,'http://geobank.sa.cprm.gov.br/cgi-bin/wmsserver/wmsRelevo?','Relevo do Brasil SRTM','WMS');
INSERT INTO i3geoadmin_ws VALUES(0,0,'CPRM','',77,'http://geobank.sa.cprm.gov.br/cgi-bin/wmsserver/arim?','Áreas de relevante interesse minerário','WMS');
INSERT INTO i3geoadmin_ws VALUES(3,3,'IBGE','',78,'http://www.geoservicos.ibge.gov.br/geoserver/IBGE/wms?','IBGE','WMS');
INSERT INTO i3geoadmin_ws VALUES(0,0,'MPA','',79,'http://sinpesq.mpa.gov.br:80/geoserver/wms?','Ministério da Pesca e Aquicultura','WMS');
INSERT INTO i3geoadmin_ws VALUES(1,1,'ESRI','SUMMARY: This image service highlights changes to vegetation areas from 1975 to 2005 using the NDVI. DESCRIPTION: This image service highlights changes to vegetation areas from 1975 to 2005 using the NDVI. This change is generated by combining multi-temporal imagery of Landsat GLS NDVI, where R,G,B = 2005 NDVI, 1975 NDVI, 2005 NDVI. Most areas in the image will be grey, indicating no change because each pixel has relatively the same value in each band. Areas that show up green were brighter in 2005, while areas that show up in magenta were brighter in 1975 than 2005. TIME ENABLED: No. DATA SOURCE: This image service was compiled from Global Land Survey (GLS) datasets: 1975, and 2005. GLS datasets are created by the U.S. Geological Survey (USGS) and the National Aeronautics and Space Administration (NASA) using Landsat images. These global minimal-cloud cover, orthorectified Landsat data products support global assessments of land-cover, land cover-change, and ecosystem dynamics such as disturbance and vegetation health. ACCESS AND USE CONSTRAINTS: This work is licensed under a Creative Commons Attribution-Noncommercial-Share Alike 3.0 United States License. CREDITS: U.S. Geological Survey (USGS), National Aeronautics and Space Administration (NASA).',80,'http://imagery.arcgisonline.com/ArcGIS/services/LandsatGLSChange/NDVI_Change_1975_2005/ImageServer/WMSServer?version=1.3.0','Landsat GLS vegetation Change 1990 2000','WMS');
INSERT INTO i3geoadmin_ws VALUES(1,1,'FUNAI','',81,'http://mapas2.funai.gov.br/i3geo/ogc.php?tema=ti','Terras indígenas da FUNAI','WMS');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','',82,'http://openlayers.org/dev/examples/kml/sundials.kml','Relógios de sol (externo)','KML');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','',83,'http://adn.agi.com/SatelliteDatabase/KmlNetworkLink.aspx','Satélites (3d)','KML');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','',84,'http://localhost/i3geo/aplicmap/dados/sundials.kml','Relógios de sol (localhost)','KML');
INSERT INTO i3geoadmin_ws VALUES(0,0,'','Cidade de Cascavel',85,'http://geoportal.cascavel.pr.gov.br/geoserver/cascavel/wms','Cascavel - PR','WMS');
COMMIT;
