<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Category" content="i3Geo Mapa interativo MMA geoprocessamento sig mobile">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
<meta name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0">
<title>i3GEO - Google Maps</title>
<script type="text/javascript"
	src="http://maps.google.com/maps/api/js?sensor=false&libraries=drawing,geometry"></script>
<script src="../js/i3geo.js"></script>
<script src="config.php?tipo=GM"></script>
<link rel="stylesheet" type="text/css" href="../css/black.css">

</head>
<body id="i3geo" style='background: white; overflow: hidden;'>

	<!-- inclui o nome do usuario logado -->
	<div id="i3GEONomeLogin"
		style="position: absolute; left: 10px; top: 12px; font-size: 11px; z-index: 50000"></div>
	<table id='mst' summary="" style='display: none;' width=100% cellspacing='0'>
		<tr>
			<td class=verdeclaro id=contemImg style="vertical-align: top; border-width: 0px;">
				<div id=googlemapsdiv
					style="position: relative; background-image: url('../imagens/i3geo1bw.jpg');"></div>
			</td>
		</tr>
	</table>
	<div id="i3GEOlogoMarca">
		<table>
			<tr>
				<td>
					<div id=versaoi3geo></div>
					<h1 class="i3GEOlogoMarca">i3Geo - Software livre para cria&ccedil;&atilde;o de mapas
						interativos e geoprocessamento</h1>
					<h1 class="i3GEOlogoMarca">Baseado no Mapserver, &eacute; licenciado sob GPL e integra o Portal
						do Software P&uacute;blico Brasileiro</h1>
				</td>
			</tr>
		</table>
		<img src='../imagens/logo_inicio.png'>
	</div>
	<div id="contemMenu">
		<!--menu suspenso-->
		<div id="menus"></div>
	</div>
	<!-- aqui ser&aacute; inclu&iacute;da a escala num&eacute;rica -->
	<div id=escala class=fundoRodape style="margin-left: 100px;"></div>

	<!-- aqui ser&aacute; inclu&iacute;do o gadget que mostra a coordenada geogr&aacute;fica da posi&ccedil;&atilde;o do mouse -->
	<div id=localizarxy class="fundoRodape" style="margin-left: 100px;"></div>

	<!-- mensagem de copyright -->
	<div id="i3GEOcopyright">i3Geo</div>

	<div id="i3GEOguiaMovel"
		style="visibility: hidden; position: absolute; display: block; border: 0px solid white; text-align: left; z-index: 2000; background-color: none">
		<div
			style="cursor: pointer; position: absolute; top: 10px; width: 30px; z-index: 5000; left: 18px;">
			<div id="iconeGuia_temas"></div>
			<div id="iconeGuia_adiciona" style="margin-top: 3px;"></div>
			<div id="iconeGuia_legenda" style="margin-top: 3px;"></div>
			<div id="iconeGuia_dobraPagina" style="margin-top: 3px;"></div>
			<div id="iconeGuia_buscaRapida" style="margin-top: 3px;"></div>
			<div id="iconeGuia_identificaBalao" style="margin-top: 3px;"></div>
			<div id="iconeGuia_identifica" style="margin-top: 3px;"></div>
			<!--
			<div id="iconeGuia_zoomtot" style="margin-top: 3px;"></div>
			<div id="iconeGuia_zoomanterior" style="margin-top: 3px;"></div>
			<div id="iconeGuia_zoomli" style="margin-top: 3px;"></div>
			<div id="iconeGuia_zoomproximo" style="margin-top: 3px;"></div>
			-->
		</div>
		<div id="i3GEOguiaMovelMolde"
			style="top: 0px; box-shadow: 0 2px 10px 0 #888888; position: absolute; display: none; border: 0px solid white; text-align: left; z-index: 1000; background-color: gray">
			<div id="i3GEOguiaMovelConteudo"
				style='top: 10px; overflow: auto; display: none; position: absolute; border-color: gray; border-width: 0px 0 0px 0px; left: 0px; height: 0px; background-color: white'>
				<div id='guia1obj' style='display: none;'>
					<div onclick="i3GEO.guias.guiaMovel.abreFecha('fecha');"
						style='cursor: pointer; left: 0px; top: 0px; width: 95%; text-align: right; font-size: 14pt;'>X</div>
					<!-- opcoes como um botao -->
					<div id="arvoreCamOpcoes" style="text-align:left;"></div>
					<!--	Esta div acrescenta a lista de de camadas dispon&iacute;veis no mapa atual -->
					<div id=listaTemas style='top: 15px;'></div>
				</div>
				<div id='guia2obj' style='display: none;'>
					<div onclick="i3GEO.guias.guiaMovel.abreFecha('fecha');"
						style='cursor: pointer; left: 0px; top: 0px; width: 95%; text-align: right; font-size: 14pt;'>X</div>
					<div id="arvoreAdicionaTema">Aguarde...</div>
				</div>
				<div id='guia4obj' style='display: none; text-align: left'>
					<div onclick="i3GEO.guias.guiaMovel.abreFecha('fecha');"
						style='cursor: pointer; left: 0px; top: 0px; width: 95%; text-align: right; font-size: 14pt;'>X</div>
					<div id="arvoreLegenda" style='display: block; text-align: left'>Aguarde...</div>
				</div>
				<div id='guia7obj' style='display: none; text-align: left'>
					<div onclick="i3GEO.guias.guiaMovel.abreFecha('fecha');"
						style='cursor: pointer; left: 0px; top: 0px; width: 95%; text-align: right; font-size: 14pt;'>X</div>
					<div id="buscaRapidaGuia" style='display: block; text-align: left'></div>
				</div>
			</div>
		</div>
	</div>
	<script>
	i3GEO.cria();
	i3GEO.inicia();
	</script>
</body>
</html>
