<?php
include_once("../ms_configura.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Category" content="I3Geo Mapa interativo MMA">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
    <style type="text/css">
        .olControlEditingToolbar  {
            float:left;
            right: 0px;
            height:30px; 
            width: 150px;
        }
</style>
<title>i3GEO - GoogleMaps</title>
</head>
<body id="i3geo" >
<center>
<table id='mst' summary="" style='display:none' width=100% cellspacing='0'>
<tr style="border:0px">
	<td colspan=2 id="barraSuperior" style="background-image:url('../imagens/visual/default/cabeca.png');height:10px"></td>
</tr>
<tr>
<td>
  <table width=100% cellspacing=0 cellpadding=0 >
   <tr>
   <td title="libera guias" class=tdclaro id=encolheFerramentas style="vertical-align:top;width:5px;text-align:left;"></td>
   <td>
    <div class=verdeescuro style="top:0px;cursor:pointer;">
	 <div id=guia1 class=guia ></div>
	 <div id=guia2 class=guia ></div>
	 <div id=guia4 class=guia ></div>
	 <div id=guia5 class=guia ></div>
    </div>
   </td>
   </tr>
  </table>
</td>
<td id="contemMenu" style="text-align:right;height:0px;border-width:0pt 0pt 1px;border-color:rgb(240,240,240)">
	 <div id="menus" ></div>    
</td>
</tr>
<tr>
 <td class=tdbranca id=contemFerramentas style="vertical-align:top;width:300px;text-align:left;">
  <div id='guia1obj' >
  	<div style='left:5px;top:10px;' id=buscaRapida ></div>
  	<div id=listaPropriedades style='top:15px;' ></div>
  	<div id=listaTemas style='top:15px;'></div>
  </div>
  <div id='guia2obj' style='display:none;'>Aguarde...<img alt="" src="../imagens/branco.gif" width=248 /></div>
  <div id='guia4obj' style='display:none;text-align:left'><div id='legenda' style='text-align:left'></div></div>
  <div id='guia5obj' style='display:none;text-align:left'><div id='banners' style='overflow:auto;text-align:left'>Aguarde...</div></div>
 </td>
 <td style="vertical-align:top;border-width:0px;">
  <table width="100%" style="vertical-align:top;border-width:0px">
   <tr><td  class=verdeclaro id=contemImg >
    <div id=googlemapsdiv style="background-image:url('../imagens/i3geo1bw.jpg');"></div>
   </td></tr>
  </table>
 </td>
 </tr>
<tr>
 <td class=tdbranca >
 	<div id="seletorIdiomas" ></div>
 	<div id=tempoRedesenho style=color:green;background-color:black;width:50px;display:none ></div>
 </td>
 <td class=tdbranca >
  <table width=100% ><tr>
  <td class=tdbranca >
  </td>
  <td class=tdbranca style=text-align:center >
	<div id=escala ></div>
  </td>
  <td class=tdbranca >
    	<div id=inserirKml ></div>
  </td>
  <td class=tdbranca >
  	<div id=localizarxy ></div>
  </td>
  </tr>
  <tr><td></td><td class="tdbranca"><div style="text-align:left;font-size:10px;background-color:white;display:none;" id=mostraUTM ></div></td><td></td></tr>
  </table>
 </td>
</tr>
<tr style="border:0px"><td colspan=3 id="barraInferior" style="background-image:url('../imagens/visual/default/rodape.png');height:10px"></td></tr>
<tr style="border:0px"><td colspan=3 style=background-color:black ><input style="border:0px none; background-color:black;color:white;font-size:12pt;" type="text" size="1" id="i3geo_letreiro" ></td></tr>
<tr style="border:0px"><td colspan=3 style=background-color:black;color:white  id="emailInstituicao">geoprocessamento@mma.gov.br</td></tr>
</table>
</center>
<center>
<br><br>
<table>
<tr>
	<td><center><h1><div id=versaoi3geo ></div><h2 style="font-size:10px;font-family: Verdana, Arial, Helvetica, sans-serif;" >i3Geo - Software livre para criação de mapas interativos e geoprocessamento<h3 style="font-size:10px;font-family: Verdana, Arial, Helvetica, sans-serif;" >Baseado no Mapserver, é licenciado sob GPL e integra o Portal do Software Público Brasileiro</h3></h2></h1></td>
</tr>
<tr>
	<td style="padding:10px;"><center><img alt="logomarca" src='../imagens/logo_inicio.png'></td>
</tr>
<tr>
	<td><center>
		<!--<script type="text/javascript" src="http://www.ohloh.net/p/150688/widgets/project_users.js?style=red"></script>-->
	</td>
</tr>
</table>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="../classesjs/i3geo.js"></script>
<script type="text/javascript">
/*
Title: Google Maps 

Abre o i3geo com a navegação controlada pelo Google Maps.

Arquivo: i3geo/interface/googlemaps.phtml

Exemplo:

http://localhost/i3geo/interface/googlemaps.phtml

*/
/*
	Indica a localização correta do i3geo.
	
	É utilizada para identificar o local correto onde estão os programas em php que são utilizados.
	
	Se não for definida, o i3Geo tentará encontrar o local automaticamente
*/
//i3GEO.configura.locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";

i3GEO.configura.locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";
i3GEO.Interface.ATUAL = "googlemaps";
i3GEO.Interface.IDCORPO = "contemImg";
i3GEO.configura.diminuixN = 20;

i3GEO.cria();

i3GEO.barraDeBotoes.TIPO = "olhodepeixe";
i3GEO.barraDeBotoes.OFFSET = -220;
i3GEO.barraDeBotoes.MAXBOTOES = 10;
//barra de botoes normal. descomente para usar
/*
i3GEO.barraDeBotoes.TIPO = "yui";
i3GEO.barraDeBotoes.AUTOALTURA = false;
i3GEO.barraDeBotoes.ATIVAMENUCONTEXTO = false;
i3GEO.barraDeBotoes.PERMITEFECHAR = true;
i3GEO.barraDeBotoes.PERMITEDESLOCAR = true;
i3GEO.barraDeBotoes.AUTO = true;
i3GEO.barraDeBotoes.COMPORTAMENTO = "laranja";
i3GEO.Interface.BARRABOTOESLEFT = 80;
i3GEO.Interface.BARRABOTOESTOP = 20;
*/
i3GEO.idioma.IDSELETOR = "seletorIdiomas";
i3GEO.Interface.ATIVAMENUCONTEXTO = true;
i3GEO.arvoreDeTemas.TIPOBOTAO = "radio";
i3GEO.arvoreDeTemas.ATIVATEMAIMEDIATO = true;
//para evitar a entrada de comentários na árvore de camadas, modifique a opção de cada tema individualmente no sistema de administração
i3GEO.arvoreDeTemas.OPCOESADICIONAIS.comentario = true;
i3GEO.mapa.AUTORESIZE = true;
i3GEO.arvoreDeCamadas.MOSTRALISTAKML = false;
//
//substitui a janela de alerta normal do navegador por uma janela estilizada. Pode ser comentado sem problemas.
//
//i3GEO.janela.ativaAlerta();
i3GEO.inicia();
</script>
</body>
</html>