<?php
include_once("../ms_configura.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Category" content="i3Geo Mapa interativo MMA geoprocessamento sig mobile">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
<title>i3GEO - Google Maps</title>

</head>
<body id="i3geo">
<table id='mst' summary="" style='display:none;' width=100% cellspacing='0'>
	<tr style="border:0px">
		<td id="barraSuperior" style="background-image:url('../imagens/visual/default/cabeca.png');height:10px"></td>
	</tr>
	<tr>
		<td id="contemMenu" style="text-align:right;border-width:0pt 0pt 1px;border-color:rgb(240,240,240)">
			<!--menu suspenso-->
			<div id="menus" ></div>
		</td>
	</tr>
	<tr>
		<td style="vertical-align:top;border-width:0px;">
			<table width="100%" style="vertical-align:top;border-width:0px">
				<tr>
					<td  class=verdeclaro id=contemImg >
						<div id=googlemapsdiv style="position:relative;background-image:url('../imagens/i3geo1bw.jpg');"></div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table width=100% >
				<tr>
					<td class=tdbranca >
						<!--
						Nesse div são incluídos os ícones que permitem ao usuário modificar o visual de cores dos ícones
						<div id=visual ></div>
						-->
						<!-- botão de compartilhamento em redes sociais -->
						<div id=i3GEOcompartilhar style="text-align:left;border-top:1px solid rgb(250,250,250);padding-top:1px" ></div>
						<!-- aqui será incluído o contador de tempo quando o temporizador de redesenho do mapa estiver ativo -->
						<div id=tempoRedesenho style=color:green;background-color:black;width:50px;display:none ></div>
					</td>
					<td class=tdbranca >
						<!-- aqui será incluída a escala numérica -->
						<div id=escala style="text-align:right;" ></div>
					</td>
					<td class=tdbranca  >
						<!-- aqui será incluído o gadget que mostra a coordenada geográfica da posição do mouse -->
						<div id=localizarxy style="text-align:left;font-size:10px;display:inline-table"></div>
					</td>
					<!-- aqui serão incluídas as bandeiras que permitem a troca de idioma -->	  
					<td class=tdbranca  >
						<div id=seletorIdiomas ></div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr style="border:0px">
		<td id="barraInferior" style="background-image:url('../imagens/visual/default/rodape.png');height:10px"></td>
	</tr>
</table>
<center>
<table id="i3GEOlogoMarca">
	<tr>
		<td><center><h1 style="font-size:10px;font-family: Verdana, Arial, Helvetica, sans-serif;"><div id=versaoi3geo ></div><h2 style="font-size:10px;font-family: Verdana, Arial, Helvetica, sans-serif;">i3Geo - Software livre para criação de mapas interativos e geoprocessamento<h3 style="font-size:10px;font-family: Verdana, Arial, Helvetica, sans-serif;">Baseado no Mapserver, é licenciado sob GPL e integra o Portal do Software Público Brasileiro</h3></h2></h1></td>
	</tr>
	<tr>
		<td style="padding:10px;"><center><img alt="logomarca" src='../imagens/logo_inicio.png'></td>
	</tr>
	<tr>
		<td><center>
			<!--
			<script id="ohloh" type="text/javascript" src="http://www.ohloh.net/p/150688/widgets/project_users.js?style=red"></script>
			-->
		</td>
	</tr>
</table>

<div id="i3GEOguiaMovel" style="position:absolute;display:block;border:0px solid white;text-align:left;z-index:1000;background-color:none">
	<img id='i3GEOguiaMovelPuxador' onclick='i3GEO.guias.guiaMovel.abreFecha()' style='z-index:2;border:solid 0px white;left:0px;position:absolute;top:0px' width='0px' src='../imagens/openbars.png' >
	<div id="i3GEOguiaMovelMolde" style="position:absolute;display:none;border:0px solid white;text-align:left;z-index:1000;background-color:gray">
		<div id='i3GEOguiaMovelIcones' style='overflow:none;left:0px;display:none;position:absolute;top:0px;text-align:center;height:0px;width:0px;border:solid 0px white;background-color:white' ></div>
		<div id='i3GEOguiaMovelConteudo' style='overflow:auto;display:none;position:absolute;border-color:gray;border-width:0px 0 0px 0px;left:0px;height:0px;background-color:white'>
			<div id='guia1obj' style='display:none;' >
				<!-- Esta div acrescenta a opção de busca rápida, caso vc queira colocá-la em um lugar específico -->
				<div style='left:5px;top:10px;' id=buscaRapida ></div>
				<!--	Esta div acrescenta a lista de propriedades do mapa -->	
				<div id=listaPropriedades style='top:15px;' ></div>
				<!--	Esta div acrescenta a lista de de camadas do tipo 'baselayers' específicas da interface Openlayers. Veja também a opção i3GEO.Interface.openlayers.GADGETS.LayerSwitcher -->
				<div id=listaLayersBase style='top:15px;'></div>
				<!--	Esta div acrescenta a lista de de camadas disponíveis no mapa atual -->
				<div id=listaTemas style='top:15px;'></div>
			</div>
			<div id='guia2obj' style='display:none;'>Aguarde...<img alt="" src="../imagens/branco.gif" width=248 /></div>
			<div id='guia4obj' style='display:none;text-align:left'><div id='legenda' style='text-align:left'></div></div>
			<div id='guia5obj' style='display:none;text-align:left'><div id='banners' style='overflow:auto;text-align:left'>Aguarde...</div></div>
		</div>
	</div>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="../classesjs/i3geonaocompacto.js"></script>
<script type="text/javascript">
/*
Title: Google Maps 

Abre o i3geo com a navegação controlada pelo Google Maps.

Arquivo: i3geo/interface/googlemaps.phtml

Exemplo:

http://localhost/i3geo/interface/googlemaps.phtml

*/
/*
	Indica a localização correta do i3geo.
	
	É utilizada para identificar o local correto onde estão os programas em php que são utilizados.
	
	Se não for definida, o i3Geo tentará encontrar o local automaticamente
*/
//i3GEO.configura.locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";

i3GEO.configura.locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";
i3GEO.Interface.ATUAL = "googlemaps";
i3GEO.Interface.IDCORPO = "contemImg";
i3GEO.configura.diminuixN = 20;

i3GEO.cria();

/*
	Inicializa o mapa
*/
//não mostra o mapa de referência
i3GEO.configura.mapaRefDisplay = "none";
//tipo de barra de botões
i3GEO.barraDeBotoes.TIPO = "olhodepeixe";
//ajusta o deslocamento da barra de botões
i3GEO.barraDeBotoes.OFFSET = -10;
//ajusta a posição da barra de botões no IE
//if(navm)
//{i3GEO.barraDeBotoes.OFFSET = -45;}

//número máximo de botões na barra de botões inicial
//i3GEO.barraDeBotoes.MAXBOTOES = 10;
//remove itens dos menus que não são necessários, já que estão como ícones na barra de botões
i3GEO.configura.oMenuData["submenus"]["janelas"] = [];

//barra de botoes normal. descomente para usar
/*
i3GEO.barraDeBotoes.TIPO = "yui";
i3GEO.barraDeBotoes.AUTOALTURA = false;
i3GEO.barraDeBotoes.ATIVAMENUCONTEXTO = false;
i3GEO.barraDeBotoes.PERMITEFECHAR = true;
i3GEO.barraDeBotoes.PERMITEDESLOCAR = true;
i3GEO.barraDeBotoes.AUTO = true;
i3GEO.barraDeBotoes.COMPORTAMENTO = "laranja";
i3GEO.Interface.BARRABOTOESLEFT = 80;
i3GEO.Interface.BARRABOTOESTOP = 20;
*/
i3GEO.idioma.IDSELETOR = "seletorIdiomas";
i3GEO.Interface.ATIVAMENUCONTEXTO = true;
i3GEO.arvoreDeTemas.TIPOBOTAO = "radio";
i3GEO.arvoreDeTemas.ATIVATEMAIMEDIATO = true;
//para evitar a entrada de comentários na árvore de camadas, modifique a opção de cada tema individualmente no sistema de administração
i3GEO.arvoreDeTemas.OPCOESADICIONAIS.comentario = true;
i3GEO.mapa.AUTORESIZE = true;
i3GEO.arvoreDeCamadas.MOSTRALISTAKML = false;
i3GEO.guias.TIPO = "movel";
i3GEO.ajuda.ATIVAJANELA = false;
//
//substitui a janela de alerta normal do navegador por uma janela estilizada. Pode ser comentado sem problemas.
//
//i3GEO.janela.ativaAlerta();
//esconde a logomarca ao finalizar o mapa
i3GEO.finaliza = function(){
	$i("i3GEOlogoMarca").style.display = "none";
}
i3GEO.inicia();
</script>
</body>
</html>