<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Category" content="i3Geo Mapa interativo MMA geoprocessamento sig mobile">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>i3GEO - OpenLayers</title>
<script src="../pacotes/ol3/ol-debug.js"></script>
<script src="../js/i3geonaocompacto.js"></script>
<link rel="stylesheet" type="text/css" href="../css/black.css">
<link rel="stylesheet" type="text/css" href="../pacotes/ol3/ol.css">
<style>
.ol-attribution img {
	display: none;
}

.ol-attribution.ol-uncollapsible {
	height: 2.1em;
	right: 24px;
	background: none;
	margin-bottom: 15px;
}

</style>
</head>
<body id="i3geo" style='margin-left: 7px; background: white;'>
<div id=contemImg >
<div id=corpoMapa ></div>
</div>
	<script>
		i3GEO.configura.locaplic = i3GEO.util.protocolo() + "://" + window.location.host + "/i3geo";
		i3GEO.configura.autotamanho = false;
		i3GEO.Interface.ATUAL = "openlayers";
		i3GEO.Interface.IDCORPO = "contemImg";
		i3GEO.gadgets.PARAMETROS.mostraMenuSuspenso.permiteLogin = true;
		i3GEO.Interface.openlayers.googleLike = true;
		i3GEO.Interface.openlayers.TILES = true;

		i3GEO.configura.guardaExtensao = false;
		i3GEO.gadgets.PARAMETROS.mostraMenuSuspenso.finaliza =
			'if($i("omenudataInterface1")){i3GEOoMenuBar.getMenuItem("omenudataInterface1").cfg.setProperty("text", " ");}';

		i3GEO.cria();
		i3GEO.configura.mapaRefDisplay = "none";
		i3GEO.barraDeBotoes.ATIVA = true;
		i3GEO.barraDeBotoes.TIPO = "olhodepeixe";
		//ajusta o deslocamento da barra de botoes
		i3GEO.barraDeBotoes.OFFSET = 11;
		//ajusta a posicao da barra de botoes no IE
		if (navm) {
			i3GEO.barraDeBotoes.OFFSET = 5;
		}
		if (chro) {
			i3GEO.barraDeBotoes.OFFSET = 15;
		}

		i3GEO.configura.oMenuData["submenus"]["janelas"] = [];
		i3GEO.ajuda.ATIVAJANELA = false;
		i3GEO.idioma.IDSELETOR = "seletorIdiomas";

		//i3GEO.arvoreDeTemas.TIPOBOTAO = "radio";
		i3GEO.arvoreDeTemas.OPCOESADICIONAIS.comentarios = true;
		i3GEO.arvoreDeCamadas.VERIFICAABRANGENCIATEMAS = true;
		i3GEO.arvoreDeCamadas.MOSTRALISTAKML = false;
		i3GEO.arvoreDeCamadas.MOSTRATITULO = true;
		i3GEO.mapa.AUTORESIZE = true;
		i3GEO.guias.TIPO = "movel";
		i3GEO.guias.guiaMovel.config.topGuiaMovel = 36;
		i3GEO.janela.ativaAlerta();
		i3GEO.finaliza = function() {
			if ($i("i3GEOlogoMarca")) {
				$i("i3GEOlogoMarca").style.display = "none";
			}
			//i3GEO.mapa.insereDobraPagina("googlemaps", "../imagens/dobragooglemaps.png");
		};
		//indica se a opcao de navegacao nas pastas do servidor sera ativada
		i3GEO.arvoreDeTemas.OPCOESADICIONAIS.navegacaoDir = true;
		i3GEO.janela.TRANSICAOSUAVE = true;
		//desliga a camada com o mapa mundi
		i3GEO.configura.mashuppar = "&desligar=mundo";
		(function() {
			var attribOSMData = 'Map Data: &copy; <a href="http://www.openstreetmap.org/">OpenStreetMap</a> contributors';
			var attribMapQuestOSM = attribOSMData + ', Tiles Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">';
			var attribMapQuestAerial = 'Map Data: &copy; Portions Courtesy NASA/JPL-Caltech and U.S. Depart. of Agriculture, Farm Service Agency, Tiles Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">';
			var attribOpenCycleMap = 'Map Data: &copy; <a href="http://www.openstreetmap.org/">OpenStreetMap</a> contributors';
			var attribDEMData = '<a href="http://srtm.csi.cgiar.org/">SRTM</a>; ASTER GDEM is a product of <a href="http://www.meti.go.jp/english/press/data/20090626_03.html">METI</a> and <a href="https://lpdaac.usgs.gov/products/aster_policies">NASA</a>';
			var attribStamen = 'Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under CC BY SA';
			var mapSurfer = 'Map data © OpenStreetMap contributors, Imagery GIScience Research Group @ Heidelberg University';

			var osm = new ol.layer.Tile({
				title : "OSM Layer",
				visible : true,
				isBaseLayer : true,
				name : "osm",
				source: new ol.source.OSM({
			    	  attributions : [new ol.Attribution({html: attribOSMData})],
			    	  crossOrigin : "anonymous",
			    	  url : "http://tile.openstreetmap.org/{z}/{x}/{y}.png",
			    	  projection: 'EPSG:3857'
			      })
			    });
			tdb = new ol.layer.Tile({
				  name : "tdb",
				  isBaseLayer : true,
				  title : "OSM Tile",
				  visible : true,
			      source: new ol.source.TileDebug({
			        projection: 'EPSG:3857',
			        tileGrid: new ol.source.OSM().getTileGrid()
			      })
			    });
			i3GEO.Interface.openlayers.LAYERSADICIONAIS = [osm,tdb];

			/*

			var eng = new ol.layer.Tile({
				title : "ESRI National Geographic",
				visible : true,
				isBaseLayer : true,
				name : "eng",
				source : new ol.source.TileArcGISRest({
					url : "http://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer",
					attributions: [
						new ol.Attribution({
							html: 'Tiles &copy; <a href="http://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer">ArcGIS</a>'
						})
					]
				})
			});
			var oce = new ol.layer.Tile({
				title : "ESRI Ocean Basemap",
				visible : false,
				isBaseLayer : true,
				name : "oce",
				source : new ol.source.TileArcGISRest({
					url : "http://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer",
					attributions: [
						new ol.Attribution({
							html: 'Tiles &copy; <a href="http://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer">ArcGIS</a>'
						})
					]
				})
			});
			var ims = new ol.layer.Tile({
				title : "ESRI Imagery World 2D",
				visible : false,
				isBaseLayer : true,
				name : "ims",
				source : new ol.source.TileArcGISRest({
					url : "http://server.arcgisonline.com/ArcGIS/rest/services/ESRI_Imagery_World_2D/MapServer",
					attributions: [
						new ol.Attribution({
							html: 'Tiles &copy; <a href="http://server.arcgisonline.com/ArcGIS/rest/services/ESRI_Imagery_World_2D/MapServer">ArcGIS</a>'
						})
					]
				})
			});
			var wsm = new ol.layer.Tile({
				title : "ESRI World Street Map",
				visible : false,
				isBaseLayer : true,
				name : "wsm",
				source : new ol.source.TileArcGISRest({
					url : "http://server.arcgisonline.com/ArcGIS/rest/services/ESRI_StreetMap_World_2D/MapServer",
					attributions: [
						new ol.Attribution({
							html: 'Tiles &copy; <a href="http://server.arcgisonline.com/ArcGIS/rest/services/ESRI_StreetMap_World_2D/MapServer">ArcGIS</a>'
						})
					]
				})
			});
			var bra = new ol.layer.Tile({
				title : "Base carto MMA",
				visible : false,
				isBaseLayer : true,
				name : "bra",
				source : new ol.source.TileWMS({
					url : "http://mapas.mma.gov.br/cgi-bin/mapserv?map=/opt/www/html/webservices/baseraster.map&",
					params : {
						'layers' : "baseraster",
						'srs' : "EPSG:4326",
						'format' : "image/png"
					}
				})
			});
			var tms = new ol.layer.Tile({
				title : "OSGEO",
				visible : false,
				isBaseLayer : true,
				name : "tms",
				source : new ol.source.TileWMS({
					url : "http://tilecache.osgeo.org/wms-c/Basic.py/",
					params : {
						'layers' : "basic",
						'type' : "png",
						'srs' : "EPSG:4326",
						'format' : "image/png",
						'VERSION' : '1.1.1'
					},
					attributions: [
						new ol.Attribution({
							html: '&copy; <a href="http://www.tilecache.org/">2006-2010, TileCache Contributors</a>'
						})
					]
				})
			});
			i3GEO.Interface.openlayers.LAYERSADICIONAIS = [
				eng, oce, ims, wsm, bra, tms
			];
			*/
		})();

		i3GEO.inicia();
	</script>
</body>
</html>
