<?php
include_once("../ms_configura.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Category" content="I3Geo Mapa interativo MMA">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
    <style type="text/css">
        .olControlEditingToolbar  {
            float:left;
            right: 0px;
            height:30px; 
            width: 150px;
        }
</style>
<title>MMA - Mapa interativo</title>
<script type="text/javascript" src="http://maps.google.com/maps?file=api&amp;v=3&amp;sensor=false&amp;key=<?php echo $googleApiKey; ?>"></script>
<script type="text/javascript" src="../classesjs/i3geo.js"></script>

</head>
<body id="i3geo" >
<center>
<table id='mst' summary="" style='display:none' width=100% cellspacing='0'>
<tr style="border:0px">
	<td colspan=2 id="barraSuperior" style="background-image:url('../imagens/visual/default/cabeca.png');height:10px"></td>
</tr>
<tr>
<td>
  <table width=100% cellspacing=0 cellpadding=0 >
   <tr>
   <td title="libera guias" class=tdclaro id=encolheFerramentas style="vertical-align:top;width:5px;text-align:left;"></td>
   <td>
    <div class=verdeescuro style="top:0px;cursor:pointer;">
	 <div id=guia1 class=guia >Temas</div>
	 <div id=guia2 class=guia >Adiciona</div>
	 <div id=guia4 class=guia >Legenda</div>
	 <div id=guia5 class=guia >Mapas</div>
    </div>
   </td>
   </tr>
  </table>
</td>
<td id="contemMenu" style="text-align:right;height:0px;border-width:0pt 0pt 1px;border-color:rgb(240,240,240)">
	 <div id="menus" ></div>    
</td>
</tr>
<tr>
 <td class=tdbranca id=contemFerramentas style="vertical-align:top;width:268px;text-align:left;">
  <div id='guia1obj' >
  	<div style='left:5px;top:10px;' id=buscaRapida ></div>
  	<div id=listaPropriedades style='top:15px;' ></div>
  	<div id=listaTemas style='top:15px;'></div>
  </div>
  <div id='guia2obj' style='display:none;'>Aguarde...<img alt="" src="../imagens/branco.gif" width=248 /></div>
  <div id='guia4obj' style='display:none;text-align:left'><div id='legenda' style='text-align:left'></div></div>
  <div id='guia5obj' style='display:none;text-align:left'><div id='banners' style='overflow:auto;text-align:left'>Aguarde...</div></div>
 </td>
 <td style="vertical-align:top;border-width:0px;">
  <table width="100%" style="vertical-align:top;border-width:0px">
   <tr><td  class=verdeclaro id=contemImg >
    <div id=googlemapsdiv style="background-image:url('../imagens/i3geo1bw.jpg');"></div>
   </td></tr>
  </table>
 </td>
 </tr>
<tr>
 <td class=tdbranca >
 	<div id=visual ></div>
 	<div id=tempoRedesenho style=color:green;background-color:black;width:50px;display:none ></div>
 </td>
 <td class=tdbranca >
  <table width=100% ><tr>
  <td class=tdbranca ></td>
  <td class=tdbranca style=text-align:center >
  	<div id=localizarxy >
  	Aguarde...
  	</div>
  </td>
  <td class=tdbranca >
    	<div id=inserirKml ></div>
  </td>
  <td class=tdbranca ><div id=ondeestou ></div></td>
  </tr>
  <tr><td></td><td class="tdbranca"><div style="text-align:left;font-size:10px;background-color:white;display:none;" id=mostraUTM ></div></td><td></td></tr>
  </table>
 </td>
</tr>
<tr style="border:0px"><td colspan=3 id="barraInferior" style="background-image:url('../imagens/visual/default/rodape.png');height:10px"></td></tr>
<tr style="border:0px"><td colspan=3 style=background-color:black ><input style="border:0px none; background-color:black;color:white;font-size:12pt;" type="text" size="1" id="i3geo_letreiro" ></td></tr>
<tr style="border:0px"><td colspan=3 style=background-color:black;color:white >geoprocessamento@mma.gov.br</td></tr>

</table>
</center>
<div id=barraDeBotoes2 style='display:none'>
	<table style="width:100%"><caption style="text-align:center">&nbsp;</caption>
	<tr><td style='background-color:rgb(250,250,250);'><img title="" alt="" src="../imagens/branco.gif" id='sobeferramentas'/></td></tr>
	</table>
	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img title="identifica" alt="" src="../imagens/branco.gif" id='identifica'/>
	</div>

	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img title="extensao" alt="" src="../imagens/branco.gif" id='exten'/>
	</div>                
	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img title="insere xy" alt="" src="../imagens/branco.gif" id='inserexy'/>
	</div> 
	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img title="texto" alt="" src="../imagens/branco.gif" id='textofid'/>
	</div>
	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img title="selecao" alt="" src="../imagens/branco.gif" id='selecao'/>
	</div>
	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img  title="rota" alt="" src="../imagens/branco.gif" id='rota'/>
	</div>

	<div style='display:inline;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img title="insere grafico" alt="" src="../imagens/branco.gif" id='inseregrafico'/>
	</div> 
	<div style='display:none;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img  title="scielo" alt="" src="../imagens/branco.gif" id='scielo'/>
	</div>
	<div style='display:none;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img  title="confluencias" alt="" src="../imagens/branco.gif" id='confluence'/>
	</div>
	<div style='display:none;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img  title="busca na wikipedia" alt="" src="../imagens/branco.gif" id='wiki'/>
	</div>
	<div style='display:none;background-color:rgb(250,250,250);'>
		<p style='font-size:6px;'>&nbsp;</p>
		<img  title="fotos" alt="" src="../imagens/branco.gif" id='buscafotos'/>
	</div>
   <table style="width:100%;"><tr><td style='background-color:rgb(250,250,250);'><p style='font-size:6px;'>&nbsp;</p><img title="" alt="" src="../imagens/branco.gif" id='desceferramentas'/></td></tr></table>
</div>
<script type="text/javascript">
/*
Title: Google Maps (experimental)

Abre o i3geo com a navegação controlada pelo Google Maps.

File: i3geo/aplicmap/googlemaps.htm

Exemplo:

http://localhost/i3geo/ms_criamapa.php?interface=googlemaps.phtml

*/
g_locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";
g_localimg = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo/imagens";
g_barraFerramentas1 = "nao"
g_barraFerramentas2 = "sim"
g_mapaRefDisplay = "none"
g_janelaMen = "nao";
g_mostraRosa = "nao"
g_opcoesTemas = "sim";
g_3dmap = "3dmap.map";
i3GEO.interface.ATUAL = "googlemaps";
i3GEO.interface.IDCORPO = "contemImg";
i3GEO.barraDeBotoes.BOTAOPADRAO = "identifica";

i3GEO.configura.listaDePropriedadesDoMapa = {
	"propriedades": [
		{ text: "p10", url: "javascript:i3GEO.mapa.dialogo.gradeCoord()"},
		{ text: "p12", url: "javascript:i3GEO.mapa.dialogo.autoredesenha()"}
	]
}

i3GEO.configura.oMenuData = {
	menu:[
		{nome:$trad("s1"),id:"ajudaMenu"},	
		{nome:$trad("s2"),id:"analise"},
		{nome:$trad("s4"),id:"arquivos"},
		{nome:$trad("d27"),id:"interface"}
	],
	submenus:{
		"ajudaMenu": [ 
			{ text: $trad("u1"), url: "http://www.softwarepublico.gov.br/spb/ver-comunidade?community_id=1444332", target:"_blank" },
			{ text: $trad("u2"), url: "javascript:i3GEO.ajuda.abreDoc()" },
			{ text: $trad("u3"), url: "http://pt.wikibooks.org/wiki/I3geo", target:"_blank" },
			{ text: $trad("u4"), url: "http://mapas.mma.gov.br/wikibooki3geo", target:"_blank" },
			{ text: $trad("u5a"), url: "http://www.softwarepublico.gov.br", target:"_blank" },
			{ text: "i3Geo Blog", url: "http://sistemas.mma.gov.br/blogs/index.php?blog=6", target:"_blank" },
			{ text: "Lista de funções", url:"http://mapas.mma.gov.br/i3geo/ajuda_usuario.php", target:"_blank" }
		],
		"analise": [
    		{ text: '<span style=color:gray;text-decoration:underline; ><b>'+$trad("u22")+'</b></span>',url: "#"}, 
			{ text: $trad("u7"), url: "javascript:i3GEO.analise.dialogo.gradePol()"},
			{ text: $trad("u8"), url: "javascript:i3GEO.analise.dialogo.gradePontos()" },
			{ text: $trad("u9"), url: "javascript:i3GEO.analise.dialogo.gradeHex()" },
    		{ text: '<span style=color:gray;text-decoration:underline; ><b>'+$trad("u23")+'</b></span>',url: "#"}, 
			{ text: $trad("u11a"), url: "javascript:i3GEO.analise.dialogo.distanciaptpt()" },
			{ text: $trad("u12"), url: "javascript:i3GEO.analise.dialogo.nptPol()" },
			{ text: $trad("u13"), url: "javascript:i3GEO.analise.dialogo.pontoempoligono()" },
			{ text: $trad("u14"), url: "javascript:i3GEO.analise.dialogo.pontosdistri()" },
    		{ text: '<span style=color:gray;text-decoration:underline; ><b>'+$trad("u24")+'</b></span>',url: "#"}, 
			{ text: $trad("u11"), url: "javascript:i3GEO.analise.dialogo.centroide()" },
			{ text: $trad("u25"), url: "javascript:i3GEO.analise.dialogo.dissolve()" },
    		{ text: '<span style=color:gray;text-decoration:underline; ><b>'+$trad("u27")+'</b></span>',url: "#"}, 
			{ text: $trad("u6"), url: "javascript:i3GEO.analise.dialogo.analisaGeometrias()" },
			{ text: $trad("u10"), url: "javascript:i3GEO.analise.dialogo.buffer()" },
			{ text: $trad("u26"), url: "javascript:i3GEO.analise.dialogo.agrupaElementos()" }
		],
		"arquivos": [
			{ text: $trad("u17"), url: "javascript:i3GEO.mapa.dialogo.salvaMapa()" },
			{ text: $trad("u18"), url: "javascript:i3GEO.mapa.dialogo.carregaMapa()" },
			{ text: $trad("u20"), url: "javascript:i3GEO.mapa.dialogo.convertews()" },
			{ text: $trad("u20a"), url: "javascript:i3GEO.mapa.dialogo.convertekml()" },
			{ text: $trad("u21"), url: "../geradordelinks.htm" }
		],
		"interface": [
			{ text: "Normal", url: "javascript:window.location = i3GEO.configura.locaplic+'/aplicmap/geral.htm?'+i3GEO.configura.sid" },
			{ text: "Google Earth", url: "javascript:window.location = i3GEO.configura.locaplic+'/aplicmap/googleearth.phtml?'+i3GEO.configura.sid" }
		]
	}
}

i3GEO.cria();
i3GEO.inicia();
</script>
</body>
</html>