<?php
include_once("../ms_configura.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Category" content="I3Geo Mapa interativo MMA">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
    <style type="text/css">
        .olControlEditingToolbar  {
            float:left;
            right: 0px;
            height:30px; 
            width: 150px;
        }
</style>
<title>MMA - Mapa interativo</title>
<script type="text/javascript" src="http://www.google.com/jsapi?key=<?php echo $googleApiKey; ?>"></script>
<script type="text/javascript" src="../classesjs/i3geo.js"></script>
</head>
<body id=i3geo >
<center>
<table id='mst' width=100% cellspacing='0'>
<tr style="border:0px"><td colspan=2 style="background-image:url('../imagens/visual/default/cabeca.png');height:10px"></td></tr>
<tr>
 <td class=tdbranca id=contemFerramentas style="border:0px;vertical-align:top;width:268px;text-align:left;">
  <table width=100% cellspacing=0 cellpadding=0 >
   <tr><td style="background-color:white;border-bottom:0px solid rgb(230,230,230);height:45px">
    <!-- Guias principais, não mude o ID, apenas o nome se for desejado -->
    <div style="top:0px;cursor:pointer;">
	 <div id=guia1 class=guia value="Mostra os temas atualmente inseridos no mapa e que podem estar visíveis ou não." >&nbsp;Temas&nbsp;</div>
	 <div id=guia2 class=guia value="Mostra a lista de temas disponíveis no servidor de dados, possibilitando que novos temas sejam adicionados ao mapa.">&nbsp;Adiciona&nbsp;</div>
	 <div id=guia4 class=guia value="Mostra a legnda do mapa atual." >&nbsp;Legenda&nbsp;</div>
	 <div id=guia5 class=guia value="Lista mapas já preparados, com temáticas específicas,que podem ser abertos no I3Geo">&nbsp;Mapas&nbsp;</div>
    </div>
   </td></tr>
  </table>
  <div id='guia1obj' >
	<div id=listaPropriedades style='top:15px;' ></div>
	<div id=listaTemas style='top:15px;' ></div>
  </div>
  <div id='guia2obj' style='display:none;'>Aguarde...<img alt="" src="../imagens/branco.gif" width=248 /></div>
  <div id='guia4obj' style='display:none;text-align:left'><div id='legenda' style='text-align:left'></div></div>
  <div id='guia5obj' style='display:none;text-align:left'><div id='banners' style='overflow:auto;text-align:left'>Aguarde...</div></div>
 </td>
 <td class=verdeclaro style="background-color:white;vertical-align:top;border-width:0px;">
  <table width="100%" style="vertical-align:top;">
   <!-- Corpo do mapa. Pode ser reposicionado, mas não mude os IDs -->
   <tr><td></td></tr>
   <tr><td  class=verdeclaro id=contemImg style="text-align:left;background-image:url('../imagens/i3geo1bw.jpg')">
    <div id=googleearth ></div>
   </td></tr>
  </table>
 </td>
</tr>
<tr>
 <td class=tdbranca >
 </td>
 <td class=tdbranca >
   	<div id=inserirKml ></div>
 </td>
</tr>



<tr style="border:0px"><td colspan=2 style="background-image:url('../imagens/visual/default/rodape.png');height:10px"></td></tr>
</table>
<a style=text-align:center;color:white href="mailto:edmar.moretti@mma.gov.br">Cr&iacute;ticas e sugest&otilde;es</a>
</center>
<script type="text/javascript">
/*
Title: Google Earth (experimental)

Abre o i3geo com a navegação controlada pelo Google Earth em 3d.

File: i3geo/aplicmap/googleearth.htm

Exemplo:

http://localhost/i3geo/ms_criamapa.php?interface=googleearth.phtml

*/
i3GEO.configura.locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";
var g_localimg = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo/imagens";
g_mapaRefDisplay = "none"
g_janelaMen = "nao";
g_mostraRosa = "nao"
g_opcoesTemas = "sim";
i3GEO.barraDeBotoes.COMPORTAMENTO = "laranja"
i3GEO.Interface.ATUAL = "googleearth";
i3GEO.Interface.IDCORPO = "contemImg";
i3GEO.barraDeBotoes.INCLUIBOTAO = {
	identifica: true,
	identificaBalao: true,
	mede: true,
	area: false,
	imprimir: false,
	reinicia: false,
	exten: true,
	referencia: false,
	inserexy: false,
	textofid: false,
	selecao: false,
	google: false,
	buscafotos: false,
	wiki: false,
	metar: false,
	lentei: false,
	confluence: false,
	inseregrafico: false,
	v3d: false
};
i3GEO.barraDeBotoes.BOTAOPADRAO = "";
i3GEO.barraDeBotoes.AUTO = true

i3GEO.cria();
i3GEO.inicia();

</script>

</body>
</html>