<?php
include_once("../ms_configura.php");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Category" content="I3Geo Mapa interativo MMA">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
    <style type="text/css">
        .olControlEditingToolbar  {
            float:left;
            right: 0px;
            height:30px; 
            width: 150px;
        }
</style>
<title>MMA - Mapa interativo</title>
<!-- Leitura dos programas javaScript e estilos. Pode-se ler os arquivos não compactados, bastando excluir a palavra _compacto -->
<script type="text/javascript" src="http://maps.google.com/maps?file=api&v=2.x&key=<?php echo $googleApiKey; ?>"></script>
<script type="text/javascript" src="../classesjs/i3geonaocompacto.js"></script>

</head>
<body id=i3geo >
<center>
<table id='mst' width=100% cellspacing='0'>
<tr style="border:0px"><td colspan=2 style="background-image:url('../imagens/visual/default/cabeca.png');height:10px"></td></tr>
<tr>
 <td class=tdbranca id=contemFerramentas style="border:0px;vertical-align:top;width:268px;text-align:left;">
  <table width=100% cellspacing=0 cellpadding=0 >
   <tr><td style="background-color:white;border-bottom:0px solid rgb(230,230,230);height:45px">
    <!-- Guias principais, não mude o ID, apenas o nome se for desejado -->
    <div style="top:0px;cursor:pointer;">
	 <div id=guia1 class=guia value="Mostra os temas atualmente inseridos no mapa e que podem estar visíveis ou não." >&nbsp;Temas&nbsp;</div>
	 <div id=guia2 class=guia value="Mostra a lista de temas disponíveis no servidor de dados, possibilitando que novos temas sejam adicionados ao mapa.">&nbsp;Adiciona&nbsp;</div>
	 <div id=guia4 class=guia value="Mostra a legnda do mapa atual." >&nbsp;Legenda&nbsp;</div>
	 <div id=guia5 class=guia value="Lista mapas já preparados, com temáticas específicas,que podem ser abertos no I3Geo">&nbsp;Mapas&nbsp;</div>
    </div>
   </td></tr>
  </table>
  <div id='guia1obj' ><div id=listaTemas ></div></div>
  <div id='guia2obj' style='display:none;'>Aguarde...<img alt="" src="../imagens/branco.gif" width=248 /></div>
  <div id='guia4obj' style='display:none;text-align:left'><div id='legenda' style='text-align:left'></div></div>
  <div id='guia5obj' style='display:none;text-align:left'><div id='banners' style='overflow:auto;text-align:left'>Aguarde...</div></div>
 </td>
 <td class=verdeclaro style="background-color:white;vertical-align:top;border-width:0px;">
  <table width="100%" style="vertical-align:top;">
   <!-- Corpo do mapa. Pode ser reposicionado, mas não mude os IDs -->
   <tr><td></td></tr>
   <tr><td  class=verdeclaro id=contemImg >
   </td></tr>
  </table>
 </td>
 </tr>
<tr style="border:0px"><td colspan=2 style="background-image:url('../imagens/visual/default/rodape.png');height:10px"></td></tr>
</table>
<a style=text-align:center;color:white href="mailto:edmar.moretti@mma.gov.br">Cr&iacute;ticas e sugest&otilde;es</a>
</center>
<div id="panel" class="olControlEditingToolbar" style="position:absolute;top:12px;left:265px;"></div>
<div id=botoesadic ></div>
<!-- Variáveis globais e inicialização do mapa-->
<script type="text/javascript">
/*
Title: OpenLayers (experimental)

Abre o i3geo com a navegação controlada pelo OpenLayers.

File: i3geo/aplicmap/googlemaps.htm

Exemplo:

http://<host>/i3geo/ms_criamapa.php?interface=googlemaps.phtml

*/
g_locaplic = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo";
g_localimg = i3GEO.util.protocolo()+"://"+window.location.host+"/i3geo/imagens";
g_barraFerramentas1 = "nao"
g_barraFerramentas2 = "nao"
g_mapaRefDisplay = "none"
g_janelaMen = "nao";
g_mostraRosa = "nao"
g_opcoesTemas = "sim";
g_3dmap = "3dmap.map";
i3GEO.interface.ATUAL = "googlemaps";
i3GEO.interface.IDCORPO = "contemImg";

i3GEO.cria();
i3GEO.inicia();
</script>

</body>
</html>